#!/usr/bin/env python3
"""Replicates tools/generate_sync.ps1's exact logic (Python instead of PowerShell) so the
packaged sync script can be regenerated without needing Windows/PowerShell locally."""
import pathlib

script_dir = pathlib.Path(__file__).parent.resolve()
SRC_DIR = script_dir / "src"
OUTPUT_FILE = script_dir / "tools" / "sync_to_studio.lua"

PREFIXES = [
    ("game/ServerScriptService/GameServer/", "game.ServerScriptService.GameServer."),
    ("game/StarterPlayer/StarterPlayerScripts/GameClient/", "game.StarterPlayer.StarterPlayerScripts.GameClient."),
    ("shared/Modules/", "game.ReplicatedStorage.Modules."),
]

def target_for(rel_path: str):
    if rel_path.startswith("lobby/"):
        return None, None
    for prefix, target_prefix in PREFIXES:
        if rel_path.startswith(prefix):
            sub = rel_path[len(prefix):]
            normalized = sub
            for suffix in (".server.lua", ".client.lua", ".lua"):
                if normalized.endswith(suffix):
                    normalized = normalized[: -len(suffix)]
                    break
            normalized = normalized.replace("/", ".")
            target_path = target_prefix + normalized
            if rel_path.endswith(".server.lua"):
                class_name = "Script"
            elif rel_path.endswith(".client.lua"):
                class_name = "LocalScript"
            else:
                class_name = "ModuleScript"
            return target_path, class_name
    return None, None

files = sorted(p for p in SRC_DIR.rglob("*") if p.is_file())

entries = []
for f in files:
    rel = f.relative_to(SRC_DIR).as_posix()
    target_path, class_name = target_for(rel)
    if not target_path:
        continue
    content = f.read_text(encoding="utf-8")
    entries.append((target_path, class_name, content))

lines = []
lines.append("-- Sync script generated by generate_sync.py (Python port of generate_sync.ps1)")
lines.append("local files = {")
for target_path, class_name, content in entries:
    lines.append("    {")
    lines.append(f'        path = "{target_path}",')
    lines.append(f'        className = "{class_name}",')
    lines.append(f"        content = [===={'['}{content}]====]")
    lines.append("    },")
lines.append("}")
lines.append("")
lines.append(r'''local function getOrCreatePath(pathStr, className)
	local parts = string.split(pathStr, ".")
	local current = game

	-- The first part is always "game" (implicit); we start from index 2.
	for i = 2, #parts - 1 do
		local name = parts[i]
		local child = current:FindFirstChild(name)
		if not child then
			child = Instance.new("Folder")
			child.Name = name
			child.Parent = current
		end
		current = child
	end

	local targetName = parts[#parts]
	local target = current:FindFirstChild(targetName)
	local isNew = false
	if not target then
		target = Instance.new(className)
		target.Name = targetName
		target.Parent = current
		isNew = true
	elseif target.ClassName ~= className then
		target:Destroy()
		target = Instance.new(className)
		target.Name = targetName
		target.Parent = current
		isNew = true
	end

	return target, isNew
end

-- Three distinct outcomes so the printed report actually tells you whether the sync did
-- anything: reallyCreated (brand-new instance), updated (existed, Source changed),
-- unchanged (existed, Source already matched -- e.g. you ran sync twice in a row).
local reallyCreated = 0
local updated = 0
local unchanged = 0
for _, file in ipairs(files) do
	local target, isNew = getOrCreatePath(file.path, file.className)
	if isNew then
		target.Source = file.content
		reallyCreated = reallyCreated + 1
	elseif target.Source ~= file.content then
		target.Source = file.content
		updated = updated + 1
	else
		unchanged = unchanged + 1
	end
end

-- Clean up the old EntityAIService under Systems if it exists (pre-v1 layout).
local oldAI = game.ServerScriptService:FindFirstChild("GameServer")
if oldAI then
	oldAI = oldAI:FindFirstChild("Systems")
	if oldAI then
		local ai = oldAI:FindFirstChild("EntityAIService")
		if ai then
			ai:Destroy()
			print("Cleaned up old Systems.EntityAIService")
		end
	end
end

return "Sync complete. New: " .. reallyCreated .. ", Updated: " .. updated .. ", Unchanged: " .. unchanged''')

OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {OUTPUT_FILE} with {len(entries)} packaged files")
