# D:\mapgameroblox\tools\generate_sync.ps1
# This script reads all local files in src/ and packages them into a single Luau script to be run in Roblox Studio.

$srcDir = "D:\mapgameroblox\src"
$outputFile = "D:\mapgameroblox\tools\sync_to_studio.lua"

$files = Get-ChildItem -Path $srcDir -Recurse -File

$luauCode = @()
$luauCode += "-- Sync script generated by generate_sync.ps1"
$luauCode += "local files = {"

foreach ($file in $files) {
    $fullName = $file.FullName
    
    # Skip lobby files
    if ($fullName -like "*\src\lobby*") {
        continue
    }
    
    $relativePath = $fullName.Substring($srcDir.Length + 1)
    
    # Determine the target path and class name
    $className = "ModuleScript"
    $targetPath = ""
    
    if ($relativePath.StartsWith("game\ServerScriptService\GameServer\")) {
        $subPath = $relativePath.Substring("game\ServerScriptService\GameServer\".Length)
        $subPathNormalized = $subPath -replace '\.server\.lua$', '' -replace '\.client\.lua$', '' -replace '\.lua$', ''
        $subPathNormalized = $subPathNormalized -replace '\\', '.'
        $targetPath = "game.ServerScriptService.GameServer." + $subPathNormalized
        
        if ($file.Name.EndsWith(".server.lua")) {
            $className = "Script"
        } elseif ($file.Name.EndsWith(".client.lua")) {
            $className = "LocalScript"
        }
    }
    elseif ($relativePath.StartsWith("game\StarterPlayer\StarterPlayerScripts\GameClient\")) {
        $subPath = $relativePath.Substring("game\StarterPlayer\StarterPlayerScripts\GameClient\".Length)
        $subPathNormalized = $subPath -replace '\.server\.lua$', '' -replace '\.client\.lua$', '' -replace '\.lua$', ''
        $subPathNormalized = $subPathNormalized -replace '\\', '.'
        $targetPath = "game.StarterPlayer.StarterPlayerScripts.GameClient." + $subPathNormalized
        
        if ($file.Name.EndsWith(".server.lua")) {
            $className = "Script"
        } elseif ($file.Name.EndsWith(".client.lua")) {
            $className = "LocalScript"
        }
    }
    elseif ($relativePath.StartsWith("shared\Modules\")) {
        $subPath = $relativePath.Substring("shared\Modules\".Length)
        $subPathNormalized = $subPath -replace '\.server\.lua$', '' -replace '\.client\.lua$', '' -replace '\.lua$', ''
        $subPathNormalized = $subPathNormalized -replace '\\', '.'
        $targetPath = "game.ReplicatedStorage.Modules." + $subPathNormalized
        
        if ($file.Name.EndsWith(".server.lua")) {
            $className = "Script"
        } elseif ($file.Name.EndsWith(".client.lua")) {
            $className = "LocalScript"
        }
    }
    
    if ($targetPath -ne "") {
        # Read the file content
        $content = [System.IO.File]::ReadAllText($fullName)
        
        # Add to the Luau code array
        $luauCode += "    {"
        $luauCode += "        path = `"$targetPath`","
        $luauCode += "        className = `"$className`","
        $luauCode += "        content = [====[" + $content + "]====]"
        $luauCode += "    },"
    }
}

$luauCode += "}"
$luauCode += ""
$luauCode += @'
local function getOrCreatePath(pathStr, className)
	local parts = string.split(pathStr, ".")
	local current = game
	
	-- The first part is always "game" (which is implicit, but parts[1] is "game")
	-- We start from index 2
	for i = 2, #parts - 1 do
		local name = parts[i]
		local child = current:FindFirstChild(name)
		if not child then
			-- If it doesn't exist, create a Folder
			child = Instance.new("Folder")
			child.Name = name
			child.Parent = current
		end
		current = child
	end
	
	local targetName = parts[#parts]
	local target = current:FindFirstChild(targetName)
	local isNew = false
	if not target then
		target = Instance.new(className)
		target.Name = targetName
		target.Parent = current
		isNew = true
	elseif target.ClassName ~= className then
		-- If it exists but class doesn't match, destroy and recreate
		target:Destroy()
		target = Instance.new(className)
		target.Name = targetName
		target.Parent = current
		isNew = true
	end
	
	return target, isNew
end

-- Three distinct outcomes so the printed report actually tells you whether the sync did
-- anything: reallyCreated (brand-new instance), updated (existed, Source changed),
-- unchanged (existed, Source already matched -- e.g. you ran sync twice in a row).
local reallyCreated = 0
local updated = 0
local unchanged = 0
for _, file in ipairs(files) do
	local target, isNew = getOrCreatePath(file.path, file.className)
	if isNew then
		target.Source = file.content
		reallyCreated = reallyCreated + 1
	elseif target.Source ~= file.content then
		target.Source = file.content
		updated = updated + 1
	else
		unchanged = unchanged + 1
	end
end

-- Also clean up the old EntityAIService under Systems if it exists
local oldAI = game.ServerScriptService:FindFirstChild("GameServer")
if oldAI then
	oldAI = oldAI:FindFirstChild("Systems")
	if oldAI then
		local ai = oldAI:FindFirstChild("EntityAIService")
		if ai then
			ai:Destroy()
			print("Cleaned up old Systems.EntityAIService")
		end
	end
end

return "Sync complete. New: " .. reallyCreated .. ", Updated: " .. updated .. ", Unchanged: " .. unchanged
'@

$luauCode | Out-File -FilePath $outputFile -Encoding utf8
Write-Host "Generated sync script at $outputFile"
