-- Sync script generated by generate_sync.ps1
local files = {
    {
        path = "game.ServerScriptService.GameServer.Bootstrap",
        className = "Script",
        content = [====[-- ServerScriptService/GameServer/Bootstrap.server.lua
-- Entry point for the Main Game place. Creates Remotes, wires every Service through a
-- shared registry table (avoids require() cycles between Services), then handles
-- per-player init/teardown. Follow MAIN_GAME_SYSTEM_RULES.md §10 for how to extend this.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")

local Modules = ReplicatedStorage:WaitForChild("Modules")
local RemoteRegistry = require(Modules.Net.RemoteRegistry)

RemoteRegistry.Init()

local ServiceScripts = script.Parent.Services

local SaveService = require(ServiceScripts.SaveService)
local TrustService = require(ServiceScripts.TrustService)
local ObjectiveService = require(ServiceScripts.ObjectiveService)
local InvestigationService = require(ServiceScripts.InvestigationService)
local DialogueService = require(ServiceScripts.DialogueService)
local PuzzleService = require(ServiceScripts.PuzzleService)
local HorrorService = require(ServiceScripts.HorrorService)
local EntityAIService = require(ServiceScripts.EntityAIService)
local CheckpointService = require(ServiceScripts.CheckpointService)
local CaseGenerationService = require(ServiceScripts.CaseGenerationService)
local AccusationService = require(ServiceScripts.AccusationService)
local NightTimerService = require(ServiceScripts.NightTimerService)
local InteractionService = require(ServiceScripts.InteractionService)

-- Shared registry passed into every Service.Init() so Services can call each other
-- (e.g. PuzzleService -> InvestigationService) without requiring each other directly.
local ServiceRegistry = {
	SaveService = SaveService,
	TrustService = TrustService,
	ObjectiveService = ObjectiveService,
	InvestigationService = InvestigationService,
	DialogueService = DialogueService,
	PuzzleService = PuzzleService,
	HorrorService = HorrorService,
	EntityAIService = EntityAIService,
	CheckpointService = CheckpointService,
	CaseGenerationService = CaseGenerationService,
	AccusationService = AccusationService,
	NightTimerService = NightTimerService,
	InteractionService = InteractionService,
}

local INIT_ORDER = {
	"SaveService",
	"TrustService",
	"ObjectiveService",
	"InvestigationService",
	"DialogueService",
	"PuzzleService",
	"HorrorService",
	"EntityAIService",
	"CheckpointService",
	"CaseGenerationService",
	"AccusationService",
	"NightTimerService",
	"InteractionService", -- last: wires ProximityPrompts to every Service above
}

for _, name in ipairs(INIT_ORDER) do
	ServiceRegistry[name].Init(ServiceRegistry)
end

local function resolveDifficulty(player)
	local joinData = player:GetJoinData()
	local teleportData = joinData and joinData.TeleportData
	if teleportData and teleportData.difficulty then
		return teleportData.difficulty
	end
	return "Easy" -- Studio / no-teleport-data fallback
end

local function onPlayerAdded(player)
	local difficulty = resolveDifficulty(player)
	player:SetAttribute("Difficulty", difficulty)

	SaveService.LoadProfile(player)
	local profile = SaveService.GetProfile(player)

	TrustService.InitPlayer(player, profile and profile.trustReputation)
	ObjectiveService.InitPlayer(player, difficulty)
	InvestigationService.InitPlayer(player)
	CheckpointService.InitPlayer(player, difficulty)
	CaseGenerationService.GenerateCase(player, difficulty)
	AccusationService.InitPlayer(player, difficulty)
	HorrorService.InitPlayer(player)
	EntityAIService.InitPlayer(player)
	NightTimerService.InitPlayer(player, difficulty)
end

local function onPlayerRemoving(player)
	SaveService.SaveProfile(player)
	TrustService.RemovePlayer(player)
	ObjectiveService.RemovePlayer(player)
	InvestigationService.RemovePlayer(player)
	CheckpointService.RemovePlayer(player)
	CaseGenerationService.RemovePlayer(player)
	AccusationService.RemovePlayer(player)
	HorrorService.RemovePlayer(player)
	EntityAIService.RemovePlayer(player)
	NightTimerService.RemovePlayer(player)
end

Players.PlayerAdded:Connect(onPlayerAdded)
Players.PlayerRemoving:Connect(onPlayerRemoving)

for _, player in ipairs(Players:GetPlayers()) do
	task.spawn(onPlayerAdded, player)
end

print("[GameServer] Bootstrap complete.")
]====]
    },
    {
        path = "game.ServerScriptService.GameServer.Services.AccusationService",
        className = "ModuleScript",
        content = [====[-- ServerScriptService/GameServer/Services/AccusationService.lua
-- Resolves accusations into endings, per DESIGN_BRIEF.md's Ending Rules and
-- game_naratif.md's Easy/Medium/Hard branches. The actual "who's guilty" answer comes
-- from CaseGenerationService's randomly generated per-player case -- NOT a static
-- lookup -- so replaying the same difficulty can point at a different suspect each time.
-- Hard mode requires BOTH a human and a pesugihan culprit to be caught (across separate
-- accusations) before it counts as fully solved; catching only one records "partial"
-- progress and keeps the game open.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local GameConfig = require(Modules.GameConfig)
local NarrativeData = require(Modules.NarrativeData)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)

local AccusationService = {}

local caughtByPlayer = {} -- [player] = { human = bool, pesugihan = bool }
local Services

function AccusationService.Init(services)
	Services = services

	RemoteRegistry.Get("Accusation/Submit").OnServerEvent:Connect(function(player, payload)
		if typeof(payload) ~= "table" then
			return
		end
		AccusationService.Submit(player, payload.suspectId)
	end)
end

function AccusationService.InitPlayer(player, _difficulty)
	caughtByPlayer[player] = { human = false, pesugihan = false }
end

function AccusationService.RemovePlayer(player)
	caughtByPlayer[player] = nil
end

-- Called by InteractionService when the `accusation_board` ProximityPrompt is triggered.
-- Sends the suspect roster + eligibility pool only -- never the actual solution.
function AccusationService.OpenBoard(player)
	RemoteRegistry.Get("Accusation/Open"):FireClient(player, {
		suspects = NarrativeData.Suspects,
	})
end

function AccusationService.Submit(player, suspectId)
	local difficulty = player:GetAttribute("Difficulty") or "Easy"

	if Services.InvestigationService.GetClueCount(player) < GameConfig.Investigation.MinCluesForAccusation then
		RemoteRegistry.Get("Accusation/Result"):FireClient(player, {
			outcome = "not_enough_clues",
			endingId = nil,
		})
		return
	end

	local culpritType = Services.CaseGenerationService.GetCulpritType(player, suspectId)

	if difficulty == "Easy" then
		if culpritType == "human" then
			Services.SaveService.RecordEnding(player, GameConfig.Ending.Easy)
			Services.SaveService.UnlockDifficulty(player, "Medium")
			RemoteRegistry.Get("Accusation/Result"):FireClient(player, {
				outcome = "correct",
				endingId = GameConfig.Ending.Easy,
			})
		else
			Services.TrustService.Adjust(player, GameConfig.Trust.Delta.WrongAccusationOfNPC, difficulty)
			RemoteRegistry.Get("Accusation/Result"):FireClient(player, { outcome = "wrong", endingId = nil })
		end
		return
	end

	if difficulty == "Medium" then
		if culpritType == "human" then
			Services.SaveService.RecordEnding(player, GameConfig.Ending.MediumHuman)
			RemoteRegistry.Get("Accusation/Result"):FireClient(player, {
				outcome = "correct",
				endingId = GameConfig.Ending.MediumHuman,
			})
		elseif culpritType == "pesugihan" then
			Services.SaveService.RecordEnding(player, GameConfig.Ending.MediumPesugihan)
			RemoteRegistry.Get("Accusation/Result"):FireClient(player, {
				outcome = "correct",
				endingId = GameConfig.Ending.MediumPesugihan,
			})
		else
			Services.TrustService.Adjust(player, GameConfig.Trust.Delta.WrongAccusationOfNPC, difficulty)
			RemoteRegistry.Get("Accusation/Result"):FireClient(player, { outcome = "wrong", endingId = nil })
		end
		return
	end

	-- Hard mode: both culprit types must be found across separate accusations.
	local caught = caughtByPlayer[player]
	if culpritType == "human" then
		caught.human = true
	elseif culpritType == "pesugihan" then
		caught.pesugihan = true
	else
		Services.TrustService.Adjust(player, GameConfig.Trust.Delta.WrongAccusationOfNPC, difficulty)
		RemoteRegistry.Get("Accusation/Result"):FireClient(player, { outcome = "wrong", endingId = nil })
		return
	end

	if caught.human and caught.pesugihan then
		Services.SaveService.RecordEnding(player, GameConfig.Ending.HardFull)
		Services.SaveService.SetFreeModeUnlocked(player, true)
		RemoteRegistry.Get("Accusation/Result"):FireClient(player, {
			outcome = "correct_full",
			endingId = GameConfig.Ending.HardFull,
		})
	else
		-- Only one culprit found so far -- game stays open, no ending screen yet.
		RemoteRegistry.Get("Accusation/Result"):FireClient(player, {
			outcome = "correct_partial",
			endingId = nil,
		})
	end
end

return AccusationService
]====]
    },
    {
        path = "game.ServerScriptService.GameServer.Services.CaseGenerationService",
        className = "ModuleScript",
        content = [====[-- ServerScriptService/GameServer/Services/CaseGenerationService.lua
-- Randomly generates each player's "solution" for the night, once per session, so the
-- guilty suspect(s) are NOT hardcoded and differ between playthroughs. This is the
-- system requested for: "Easy = selalu manusia (dipilih acak dari kandidat), Medium =
-- acak antara Story ID 1 (manusia) / Story ID 2 (pesugihan), Hard = butuh menangkap DUA
-- pelaku (satu manusia + satu pesugihan), keduanya dipilih acak dari kandidat masing-
-- masing." None of the source design docs specify random assignment explicitly (they
-- only describe the two Medium story branches and Hard's "must catch every culprit"
-- rule) -- this Service is the concrete system that makes it actually random per match,
-- built on top of those documented rules.
--
-- The generated case is NEVER sent to the client in any form. AccusationService is the
-- only thing that reads it, to compare a player's accusation against the answer.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local NarrativeData = require(Modules.NarrativeData)

local CaseGenerationService = {}

-- [player] = { branch = "human"|"pesugihan"|nil, culpritBySuspectId = { [suspectId] = role } }
local caseByPlayer = {}

function CaseGenerationService.Init(_services) end

local function poolFor(role)
	local pool = {}
	for _, suspect in ipairs(NarrativeData.Suspects) do
		for _, eligible in ipairs(suspect.eligibleRoles) do
			if eligible == role then
				table.insert(pool, suspect.id)
				break
			end
		end
	end
	return pool
end

local function pickRandom(pool)
	if #pool == 0 then
		warn("[CaseGenerationService] No eligible suspects for this role -- check NarrativeData.Suspects")
		return nil
	end
	return pool[math.random(1, #pool)]
end

-- Called once per player per match (Bootstrap.onPlayerAdded), right after Difficulty is
-- set. Re-calling it (e.g. on a rematch) generates a fresh random solution.
function CaseGenerationService.GenerateCase(player, difficulty)
	local culpritBySuspectId = {}
	local branch = nil

	if difficulty == "Easy" then
		-- Easy is always a normal human thief (per DESIGN_BRIEF.md/GAME LAVEL.md) --
		-- WHICH suspect is picked at random from the eligible pool for replayability.
		local humanId = pickRandom(poolFor("human"))
		if humanId then
			culpritBySuspectId[humanId] = "human"
		end
	elseif difficulty == "Medium" then
		-- 50/50 which story branch is true this session: Story ID 1 (human) or
		-- Story ID 2 (pesugihan), per game_naratif.md's two Medium endings.
		branch = (math.random() < 0.5) and "human" or "pesugihan"
		local suspectId = pickRandom(poolFor(branch))
		if suspectId then
			culpritBySuspectId[suspectId] = branch
		end
	else -- Hard
		-- Hard always needs BOTH a human culprit and a pesugihan culprit caught
		-- (game_naratif.md: "harus mengungkap seluruh pelaku, baik pencuri manusia
		-- maupun pihak yang terlibat dalam praktik pesugihan"). Each is picked
		-- independently at random from its own pool.
		local humanId = pickRandom(poolFor("human"))
		local pesugihanId = pickRandom(poolFor("pesugihan"))
		if humanId then
			culpritBySuspectId[humanId] = "human"
		end
		if pesugihanId then
			culpritBySuspectId[pesugihanId] = "pesugihan"
		end
	end

	caseByPlayer[player] = {
		branch = branch,
		culpritBySuspectId = culpritBySuspectId,
	}
end

function CaseGenerationService.RemovePlayer(player)
	caseByPlayer[player] = nil
end

-- Returns "human" | "pesugihan" | nil (innocent) for the given suspectId, per this
-- player's randomly generated case. This is the ONLY place AccusationService should
-- read "who's actually guilty" from -- never read NarrativeData.Suspects directly for
-- that, its eligibleRoles field is a pool, not an answer.
function CaseGenerationService.GetCulpritType(player, suspectId)
	local case = caseByPlayer[player]
	if not case then
		return nil
	end
	return case.culpritBySuspectId[suspectId]
end

-- Medium-only: which branch ("human" | "pesugihan") this session's true story is. Not
-- currently consumed anywhere, but useful if DialogueService/HorrorService later want to
-- bias flavor content toward whichever branch is actually true this session.
function CaseGenerationService.GetBranch(player)
	local case = caseByPlayer[player]
	return case and case.branch
end

return CaseGenerationService
]====]
    },
    {
        path = "game.ServerScriptService.GameServer.Services.CheckpointService",
        className = "ModuleScript",
        content = [====[-- ServerScriptService/GameServer/Services/CheckpointService.lua
-- Records the last reached checkpoint (via SaveService, plus its physical CFrame for
-- teleport-back) and unlocks an optional hint after repeated investigation failures
-- (game_mechanics.md rule #9). ReturnToLastCheckpoint() implements the "failure return"
-- half of ARCHITECTURE.md's CheckpointService description -- triggered by TrustService
-- (trust collapses to "feared") and NightTimerService (time's up, quota not met), per
-- game_mechanics.md rule #2.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local GameConfig = require(Modules.GameConfig)
local NarrativeData = require(Modules.NarrativeData)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)

local CheckpointService = {}

local failuresByPlayer = {}
local hintGivenByPlayer = {}
local lastCFrameByPlayer = {}
local Services

function CheckpointService.Init(services)
	Services = services
end

function CheckpointService.InitPlayer(player, _difficulty)
	failuresByPlayer[player] = 0
	hintGivenByPlayer[player] = false
	lastCFrameByPlayer[player] = nil
end

function CheckpointService.RemovePlayer(player)
	failuresByPlayer[player] = nil
	hintGivenByPlayer[player] = nil
	lastCFrameByPlayer[player] = nil
end

-- Called by InteractionService when a `checkpoint` ProximityPrompt is triggered.
-- `cframe` is the checkpoint part's own CFrame, read live from the map at trigger time --
-- this Service never hardcodes or caches map positions.
function CheckpointService.Reach(player, checkpointId, cframe)
	Services.SaveService.SetCheckpoint(player, checkpointId)
	if cframe then
		lastCFrameByPlayer[player] = cframe
	end
	Services.ObjectiveService.DepositCarriedJimpitan(player)
	RemoteRegistry.Get("Checkpoint/Saved"):FireClient(player, { checkpointId = checkpointId })
end

-- Teleports the player back to the last reached checkpoint. No-ops if the player hasn't
-- reached one yet (their spawn point stands in for "checkpoint zero").
function CheckpointService.ReturnToLastCheckpoint(player, reason)
	local cframe = lastCFrameByPlayer[player]
	if not cframe then
		return
	end
	local character = player.Character
	local root = character and character:FindFirstChild("HumanoidRootPart")
	if root then
		root.CFrame = cframe + Vector3.new(0, 5, 0)
	end
	RemoteRegistry.Get("Checkpoint/Returned"):FireClient(player, { reason = reason or "unknown" })
end

function CheckpointService.ReportInvestigationFailure(player)
	local count = (failuresByPlayer[player] or 0) + 1
	failuresByPlayer[player] = count

	if count >= GameConfig.Investigation.HintUnlockAfterFailures and not hintGivenByPlayer[player] then
		hintGivenByPlayer[player] = true
		RemoteRegistry.Get("Checkpoint/HintUnlocked"):FireClient(player, {
			hintText = NarrativeData.Hints.default,
		})
	end
end

return CheckpointService
]====]
    },
    {
        path = "game.ServerScriptService.GameServer.Services.DialogueService",
        className = "ModuleScript",
        content = [====[-- ServerScriptService/GameServer/Services/DialogueService.lua
-- Branching NPC dialogue driven entirely by NarrativeData. `Dialogue/Start` is called
-- directly by InteractionService when an `npc` ProximityPrompt fires (no remote needed);
-- `Dialogue/Choose` is the one client->server remote, used for follow-up choices once a
-- dialogue box is already open. A choice can optionally carry a `TrustDelta` (see
-- NarrativeData) -- game_mechanics.md's Player Actions table explicitly lists Dialogue
-- Choice as affecting trust, so this Service is where that hook lives.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local NarrativeData = require(Modules.NarrativeData)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)

local DialogueService = {}

local currentNodeByPlayer = {} -- [player] = { npcId, nodeId }
local Services

local TRUST_ORDER = { feared = 1, suspicious = 2, neutral = 3, trusted = 4 }

function DialogueService.Init(services)
	Services = services

	RemoteRegistry.Get("Dialogue/Choose").OnServerEvent:Connect(function(player, payload)
		if typeof(payload) ~= "table" then
			return
		end
		DialogueService.Choose(player, payload.nodeId, payload.choiceId)
	end)
end

local function isChoiceLocked(player, choice)
	if not choice.Requires then
		return false, nil
	end
	if choice.Requires.ClueId and not Services.InvestigationService.HasClue(player, choice.Requires.ClueId) then
		return true, "Kamu belum menemukan petunjuk yang cukup."
	end
	if choice.Requires.Trust then
		local currentState = Services.TrustService.GetState(player)
		if (TRUST_ORDER[currentState] or 0) < (TRUST_ORDER[choice.Requires.Trust] or 0) then
			return true, "Warga belum cukup percaya padamu."
		end
	end
	return false, nil
end

local function sendNode(player, npcId, nodeId)
	local npc = NarrativeData.NPCs[npcId]
	if not npc then
		return
	end
	local node = npc.Nodes[nodeId]
	if not node then
		return
	end

	currentNodeByPlayer[player] = { npcId = npcId, nodeId = nodeId }

	local choicesPayload = {}
	for _, choice in ipairs(node.Choices) do
		local locked, reason = isChoiceLocked(player, choice)
		table.insert(choicesPayload, {
			id = choice.Id,
			text = choice.Text,
			locked = locked,
			lockedReason = reason,
		})
	end

	RemoteRegistry.Get("Dialogue/Node"):FireClient(player, {
		nodeId = nodeId,
		npcName = npc.DisplayName,
		text = node.Text,
		choices = choicesPayload,
	})
end

function DialogueService.Start(player, npcId)
	local npc = NarrativeData.NPCs[npcId]
	if not npc then
		warn("[DialogueService] Unknown NPCId:", npcId)
		return
	end
	sendNode(player, npcId, npc.StartNode)
end

function DialogueService.Choose(player, nodeId, choiceId)
	local current = currentNodeByPlayer[player]
	if not current or current.nodeId ~= nodeId then
		return -- stale/forged request; ignore
	end
	local npc = NarrativeData.NPCs[current.npcId]
	local node = npc and npc.Nodes[nodeId]
	if not node then
		return
	end

	for _, choice in ipairs(node.Choices) do
		if choice.Id == choiceId then
			if isChoiceLocked(player, choice) then
				return -- client should already grey this out; server re-validates anyway
			end

			if choice.TrustDelta then
				Services.TrustService.Adjust(player, choice.TrustDelta, player:GetAttribute("Difficulty"))
			end

			if choice.Next then
				sendNode(player, current.npcId, choice.Next)
			else
				currentNodeByPlayer[player] = nil
			end
			return
		end
	end
end

return DialogueService
]====]
    },
    {
        path = "game.ServerScriptService.GameServer.Services.EntityAIService",
        className = "ModuleScript",
        content = [====[-- ServerScriptService/GameServer/Services/EntityAIService.lua
-- Non-combat observing-entity presence. Fires rarer "sighted" hints than HorrorService's
-- flicker events. NEVER becomes a chase/combat mechanic and never sends exact position
-- data that would trivialize investigation -- payload is hintOnly + an optional flavor
-- name pulled from NarrativeData.EntityNames (setan gundul / methek, per the team's
-- accepted narrative revision).

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local GameConfig = require(Modules.GameConfig)
local NarrativeData = require(Modules.NarrativeData)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)

local EntityAIService = {}

local activeLoops = {}

local function frequencyKeyFor(player)
	local difficulty = player:GetAttribute("Difficulty") or "Easy"
	local tier = GameConfig.Difficulty[difficulty]
	return (tier and tier.HorrorFrequency) or "low"
end

local function entityNameFor(player)
	local difficulty = player:GetAttribute("Difficulty") or "Easy"
	local names = NarrativeData.EntityNames[difficulty]
	if not names or #names == 0 then
		return nil
	end
	return names[math.random(1, #names)]
end

function EntityAIService.Init(_services) end

function EntityAIService.InitPlayer(player)
	activeLoops[player] = true
	task.spawn(function()
		while activeLoops[player] do
			local range = GameConfig.HorrorIntervalSeconds[frequencyKeyFor(player)]
			-- Entity sightings are intentionally rarer than horror flicker events.
			task.wait(range.min + range.max)
			if not activeLoops[player] then
				return
			end
			RemoteRegistry.Get("Entity/Sighted"):FireClient(player, {
				hintOnly = true,
				entityHint = entityNameFor(player),
			})
		end
	end)
end

function EntityAIService.RemovePlayer(player)
	activeLoops[player] = nil
end

return EntityAIService
]====]
    },
    {
        path = "game.ServerScriptService.GameServer.Services.HorrorService",
        className = "ModuleScript",
        content = [====[-- ServerScriptService/GameServer/Services/HorrorService.lua
-- Schedules subtle psychological events per difficulty intensity. STRICTLY cosmetic --
-- never mutates trust/objective/clue state. Client only receives an eventType + empty
-- params table and decides how to render it (see HorrorController.lua).

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local GameConfig = require(Modules.GameConfig)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)

local HorrorService = {}

local EVENT_TYPES = { "whisper", "shadow_flicker", "light_flicker" }
local activeLoops = {}

local function frequencyKeyFor(player)
	local difficulty = player:GetAttribute("Difficulty") or "Easy"
	local tier = GameConfig.Difficulty[difficulty]
	return (tier and tier.HorrorFrequency) or "low"
end

function HorrorService.Init(_services) end

function HorrorService.InitPlayer(player)
	activeLoops[player] = true
	task.spawn(function()
		while activeLoops[player] do
			local range = GameConfig.HorrorIntervalSeconds[frequencyKeyFor(player)]
			task.wait(range.min + math.random() * (range.max - range.min))
			if not activeLoops[player] then
				return
			end
			RemoteRegistry.Get("Horror/Event"):FireClient(player, {
				eventType = EVENT_TYPES[math.random(1, #EVENT_TYPES)],
				params = {},
			})
		end
	end)
end

function HorrorService.RemovePlayer(player)
	activeLoops[player] = nil
end

return HorrorService
]====]
    },
    {
        path = "game.ServerScriptService.GameServer.Services.InteractionService",
        className = "ModuleScript",
        content = [====[-- ServerScriptService/GameServer/Services/InteractionService.lua
-- Single entry point for every ProximityPrompt in Workspace.Map.Gameplay. Roblox's
-- ProximityPrompt already only fires .Triggered server-side after validating distance
-- (MaxActivationDistance) -- this Service just reads attributes and routes to the
-- matching Service. No Controller/Remote ever bypasses this path.
--
-- Must be Init()'d LAST in Bootstrap (after every other Service), since it calls into
-- all of them.

local Workspace = game:GetService("Workspace")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local AttributeConstants = require(Modules.Util.AttributeConstants)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)

local InteractionService = {}

local Services

local function getGameplayFolder()
	local map = Workspace:FindFirstChild("Map") or Workspace:WaitForChild("Map", 30)
	if not map then
		return nil
	end
	return map:FindFirstChild("Gameplay") or map:WaitForChild("Gameplay", 30)
end

local function difficultyAllows(part, player)
	local only = part:GetAttribute(AttributeConstants.Attributes.DifficultyOnly)
	if not only then
		return true
	end
	return player:GetAttribute("Difficulty") == only
end

-- Optional soft-lock: an interactable can require a specific clue already be collected
-- before it does anything (e.g. Rumah Kosong's false-clue location, shown padlocked in
-- the reference map). Purely a gate -- InteractionType logic is untouched otherwise.
local function meetsRequirement(part, player, services)
	local requiredClueId = part:GetAttribute(AttributeConstants.Attributes.RequiresClueId)
	if not requiredClueId then
		return true
	end
	return services.InvestigationService.HasClue(player, requiredClueId)
end

local function onTriggered(part, player)
	if not difficultyAllows(part, player) then
		return
	end
	if not meetsRequirement(part, player, Services) then
		RemoteRegistry.Get("Interaction/Locked"):FireClient(player, {
			reason = part:GetAttribute(AttributeConstants.Attributes.PromptText) or "locked",
		})
		return
	end

	local interactionType = part:GetAttribute(AttributeConstants.Attributes.InteractionType)
	local Types = AttributeConstants.InteractionType
	local Attrs = AttributeConstants.Attributes

	if interactionType == Types.Jimpitan then
		Services.ObjectiveService.AddCarriedJimpitan(player, 1)
		-- One-time pickup; MapManager.luau (environment team's script, see
		-- MAP_LEVEL_DESIGN_GUIDE.md) owns respawn behavior for JimpitanSpawns -- we only
		-- consume the interaction here, we never touch the spawn part itself.
	elseif interactionType == Types.Clue then
		Services.InvestigationService.CollectClue(
			player,
			part:GetAttribute(Attrs.ClueId),
			part:GetAttribute(Attrs.ClueText),
			part:GetAttribute(Attrs.FalseClue) == true
		)
	elseif interactionType == Types.NPC then
		Services.DialogueService.Start(player, part:GetAttribute(Attrs.NPCId))
	elseif interactionType == Types.Puzzle then
		Services.PuzzleService.Open(player, part:GetAttribute(Attrs.PuzzleId))
	elseif interactionType == Types.Checkpoint then
		Services.CheckpointService.Reach(player, part:GetAttribute(Attrs.CheckpointId), part.CFrame)
	elseif interactionType == Types.AccusationBoard then
		Services.AccusationService.OpenBoard(player)
	end
end

local function wire(prompt, part)
	prompt.Triggered:Connect(function(player)
		onTriggered(part, player)
	end)
end

local function tryWireDescendant(descendant)
	if not descendant:IsA("ProximityPrompt") then
		return
	end
	local part = descendant.Parent
	if part and part:GetAttribute(AttributeConstants.Attributes.InteractionType) then
		wire(descendant, part)
	end
end

function InteractionService.Init(services)
	Services = services

	task.spawn(function()
		local gameplayFolder = getGameplayFolder()
		if not gameplayFolder then
			warn("[InteractionService] Workspace.Map.Gameplay not found -- no interactables wired.")
			return
		end

		for _, descendant in ipairs(gameplayFolder:GetDescendants()) do
			tryWireDescendant(descendant)
		end

		gameplayFolder.DescendantAdded:Connect(tryWireDescendant)
	end)
end

return InteractionService
]====]
    },
    {
        path = "game.ServerScriptService.GameServer.Services.InvestigationService",
        className = "ModuleScript",
        content = [====[-- ServerScriptService/GameServer/Services/InvestigationService.lua
-- Owns each player's collected-clue set. `isFalse` is tracked server-side only (used by
-- HorrorService/DialogueService gating later) and is NEVER sent to the client -- the
-- client just sees a clue entry appear in the journal, same as a real one.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local RemoteRegistry = require(Modules.Net.RemoteRegistry)

local InvestigationService = {}

local cluesByPlayer = {} -- [player] = { [clueId] = { isFalse = bool } }

function InvestigationService.Init(_services) end

function InvestigationService.InitPlayer(player)
	cluesByPlayer[player] = {}
end

function InvestigationService.RemovePlayer(player)
	cluesByPlayer[player] = nil
end

function InvestigationService.CollectClue(player, clueId, clueText, isFalse)
	local clues = cluesByPlayer[player]
	if not clues or not clueId then
		return false
	end
	if clues[clueId] then
		return false -- already collected
	end
	clues[clueId] = { isFalse = isFalse == true }
	RemoteRegistry.Get("Investigation/ClueAdded"):FireClient(player, {
		clueId = clueId,
		text = clueText or "Kamu menemukan sebuah petunjuk.",
	})
	return true
end

function InvestigationService.HasClue(player, clueId)
	local clues = cluesByPlayer[player]
	return clues ~= nil and clues[clueId] ~= nil
end

function InvestigationService.GetClueCount(player)
	local clues = cluesByPlayer[player]
	if not clues then
		return 0
	end
	local count = 0
	for _ in pairs(clues) do
		count = count + 1
	end
	return count
end

return InvestigationService
]====]
    },
    {
        path = "game.ServerScriptService.GameServer.Services.NightTimerService",
        className = "ModuleScript",
        content = [====[-- ServerScriptService/GameServer/Services/NightTimerService.lua
-- Counts down the per-level "waktu ronda" from game_mechanics.md rule #1. On expiry, if
-- the player hasn't met the objective quota yet, that's a mission failure per rule #2 --
-- NOT a hard game over, just a return to the last checkpoint (mirrors what happens when
-- trust collapses into "feared", see TrustService).

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local GameConfig = require(Modules.GameConfig)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)

local NightTimerService = {}

local activeTimers = {}
local Services

function NightTimerService.Init(services)
	Services = services
end

function NightTimerService.InitPlayer(player, difficulty)
	local duration = GameConfig.Night.DurationSeconds[difficulty] or GameConfig.Night.DurationSeconds.Easy
	local deadline = os.clock() + duration
	local token = {} -- unique token so a stale loop from a previous life can't fire late
	activeTimers[player] = token

	task.spawn(function()
		while activeTimers[player] == token do
			local remaining = math.max(0, math.floor(deadline - os.clock()))
			RemoteRegistry.Get("Night/TimeUpdated"):FireClient(player, { secondsRemaining = remaining })

			if remaining <= 0 then
				local questCompleted = Services.ObjectiveService.IsQuotaMet(player)
				RemoteRegistry.Get("Night/TimeUp"):FireClient(player, { questCompleted = questCompleted })
				if not questCompleted then
					Services.CheckpointService.ReturnToLastCheckpoint(player, "time_up")
				end
				activeTimers[player] = nil
				return
			end

			task.wait(GameConfig.Night.BroadcastIntervalSeconds)
		end
	end)
end

function NightTimerService.RemovePlayer(player)
	activeTimers[player] = nil
end

return NightTimerService
]====]
    },
    {
        path = "game.ServerScriptService.GameServer.Services.ObjectiveService",
        className = "ModuleScript",
        content = [====[-- ServerScriptService/GameServer/Services/ObjectiveService.lua
-- Tracks the global cooperative objective chain per difficulty. Jimpitan collection is
-- two-phase, matching GAME_LAVEL.md's "Main Action": pick up jimpitan around the village
-- (carried, not yet counted) THEN deposit it at a checkpoint/Pos Ronda (progress) --
-- this is deliberately where the "money disappears" mystery lives narratively.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local GameConfig = require(Modules.GameConfig)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)

local ObjectiveService = {}

local progressByPlayer = {}

function ObjectiveService.Init(_services) end

function ObjectiveService.InitPlayer(player, difficulty)
	local tier = GameConfig.Difficulty[difficulty] or GameConfig.Difficulty.Easy
	progressByPlayer[player] = {
		progress = 0,
		target = tier.JimpitanQuota,
		carried = 0,
		label = "Kumpulkan jimpitan",
	}
	ObjectiveService.Broadcast(player)
end

function ObjectiveService.RemovePlayer(player)
	progressByPlayer[player] = nil
end

function ObjectiveService.Broadcast(player)
	local data = progressByPlayer[player]
	if not data then
		return
	end
	RemoteRegistry.Get("Objective/StateChanged"):FireClient(player, {
		label = data.label,
		progress = data.progress,
		target = data.target,
		carried = data.carried,
	})
end

-- Called by InteractionService when a `jimpitan_can` ProximityPrompt is triggered. Does
-- NOT count toward the objective yet -- see DepositCarriedJimpitan.
function ObjectiveService.AddCarriedJimpitan(player, amount)
	local data = progressByPlayer[player]
	if not data then
		return
	end
	data.carried = data.carried + (amount or 1)
	ObjectiveService.Broadcast(player)
end

-- Called by CheckpointService whenever the player reaches ANY checkpoint (Pos Ronda or
-- otherwise) -- converts carried jimpitan into real objective progress.
function ObjectiveService.DepositCarriedJimpitan(player)
	local data = progressByPlayer[player]
	if not data or data.carried <= 0 then
		return
	end
	local amount = data.carried
	data.carried = 0
	data.progress = math.min(data.target, data.progress + amount)
	ObjectiveService.Broadcast(player)
end

function ObjectiveService.SetLabel(player, label)
	local data = progressByPlayer[player]
	if not data then
		return
	end
	data.label = label
	ObjectiveService.Broadcast(player)
end

function ObjectiveService.IsQuotaMet(player)
	local data = progressByPlayer[player]
	return data ~= nil and data.progress >= data.target
end

return ObjectiveService
]====]
    },
    {
        path = "game.ServerScriptService.GameServer.Services.PuzzleService",
        className = "ModuleScript",
        content = [====[-- ServerScriptService/GameServer/Services/PuzzleService.lua
-- Observation-puzzle framework. Implements ONE full puzzle type end-to-end (a
-- multiple-choice "spot the anomaly" puzzle), per MAIN_GAME_SYSTEM_RULES.md Build Order
-- step 7 -- add more entries to `Puzzles` below as new PuzzleId markers are attached to
-- interactables in Workspace.Map.Gameplay.Puzzles. No client/Controller changes are
-- needed to add a new puzzle of this type.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local RemoteRegistry = require(Modules.Net.RemoteRegistry)

local PuzzleService = {}

local Puzzles = {
	rumah_02_jejak = {
		Question = "Mana jejak kaki yang tidak cocok dengan pola warga lain di rumah ini?",
		Options = {
			{ id = "a", text = "Jejak sandal, mengarah ke dapur" },
			{ id = "b", text = "Jejak sepatu bot, mengarah ke pagar belakang" },
			{ id = "c", text = "Jejak kaki telanjang, melingkar di teras" },
		},
		AnswerId = "b",
		RewardClueId = "jejak_sepatu_bot",
		RewardClueText = "Jejak sepatu bot menuju pagar belakang -- bukan pola warga biasa.",
	},
}

local activePuzzleByPlayer = {}
local Services

function PuzzleService.Init(services)
	Services = services

	RemoteRegistry.Get("Puzzle/Submit").OnServerEvent:Connect(function(player, payload)
		if typeof(payload) ~= "table" then
			return
		end
		PuzzleService.Submit(player, payload.puzzleId, payload.answer)
	end)
end

-- Called by InteractionService when a `puzzle` ProximityPrompt is triggered.
function PuzzleService.Open(player, puzzleId)
	local puzzle = Puzzles[puzzleId]
	if not puzzle then
		warn("[PuzzleService] Unknown PuzzleId:", puzzleId)
		return
	end
	activePuzzleByPlayer[player] = puzzleId
	RemoteRegistry.Get("Puzzle/Data"):FireClient(player, {
		puzzleId = puzzleId,
		question = puzzle.Question,
		options = puzzle.Options,
	})
end

function PuzzleService.Submit(player, puzzleId, answerId)
	if activePuzzleByPlayer[player] ~= puzzleId then
		return -- no active puzzle matching this id; ignore forged/stale submit
	end
	local puzzle = Puzzles[puzzleId]
	if not puzzle then
		return
	end

	local success = answerId == puzzle.AnswerId
	activePuzzleByPlayer[player] = nil

	if success then
		Services.InvestigationService.CollectClue(player, puzzle.RewardClueId, puzzle.RewardClueText, false)
	else
		Services.CheckpointService.ReportInvestigationFailure(player)
	end

	RemoteRegistry.Get("Puzzle/Result"):FireClient(player, {
		success = success,
		rewardClueId = success and puzzle.RewardClueId or nil,
	})
end

return PuzzleService
]====]
    },
    {
        path = "game.ServerScriptService.GameServer.Services.SaveService",
        className = "ModuleScript",
        content = [====[-- ServerScriptService/GameServer/Services/SaveService.lua
-- DataStore profile per PUBLISHING.md §6, extended per MAIN_GAME_SYSTEM_RULES.md §6 with
-- ending ids + freeModeUnlocked (read cross-place by the Lobby to gate Free Mode).

local DataStoreService = game:GetService("DataStoreService")
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local GameConfig = require(Modules.GameConfig)

local SaveService = {}

local store = DataStoreService:GetDataStore(GameConfig.SaveService.DataStoreName)
local profiles = {}

local DEFAULT_PROFILE = {
	checkpoint = "",
	unlockedDifficulty = "Easy",
	endingsSeen = {},
	trustReputation = GameConfig.Trust.Default,
	totalGames = 0,
	freeModeUnlocked = false,
}

local DIFFICULTY_ORDER = { Easy = 1, Medium = 2, Hard = 3 }

local function deepCopy(value)
	if typeof(value) ~= "table" then
		return value
	end
	local copy = {}
	for k, v in pairs(value) do
		copy[k] = deepCopy(v)
	end
	return copy
end

function SaveService.Init(_services) end

function SaveService.LoadProfile(player)
	local success, data = pcall(function()
		return store:GetAsync("Player_" .. player.UserId)
	end)

	if success and data then
		profiles[player] = data
	else
		if not success then
			warn("[SaveService] GetAsync failed for", player.Name, data)
		end
		profiles[player] = deepCopy(DEFAULT_PROFILE)
	end
	profiles[player].totalGames = (profiles[player].totalGames or 0) + 1
end

function SaveService.GetProfile(player)
	return profiles[player]
end

function SaveService.SaveProfile(player)
	local data = profiles[player]
	if not data then
		return
	end
	local success, err = pcall(function()
		store:SetAsync("Player_" .. player.UserId, data)
	end)
	if not success then
		warn("[SaveService] SetAsync failed for", player.Name, err)
	end
end

function SaveService.SetCheckpoint(player, checkpointId)
	local data = profiles[player]
	if data then
		data.checkpoint = checkpointId
	end
end

function SaveService.UnlockDifficulty(player, difficulty)
	local data = profiles[player]
	if not data then
		return
	end
	if (DIFFICULTY_ORDER[difficulty] or 0) > (DIFFICULTY_ORDER[data.unlockedDifficulty] or 0) then
		data.unlockedDifficulty = difficulty
	end
end

function SaveService.RecordEnding(player, endingId)
	local data = profiles[player]
	if not data then
		return
	end
	if not table.find(data.endingsSeen, endingId) then
		table.insert(data.endingsSeen, endingId)
	end
end

function SaveService.SetFreeModeUnlocked(player, value)
	local data = profiles[player]
	if data then
		data.freeModeUnlocked = value
	end
end

function SaveService.SetTrustReputation(player, value)
	local data = profiles[player]
	if data then
		data.trustReputation = value
	end
end

-- Safety net: if Bootstrap's own PlayerRemoving handler doesn't get a chance to run
-- (e.g. server crash/kick edge cases), still attempt one best-effort save.
Players.PlayerRemoving:Connect(function(player)
	task.defer(function()
		if profiles[player] then
			SaveService.SaveProfile(player)
		end
	end)
end)

return SaveService
]====]
    },
    {
        path = "game.ServerScriptService.GameServer.Services.TrustService",
        className = "ModuleScript",
        content = [====[-- ServerScriptService/GameServer/Services/TrustService.lua
-- Owns internal numeric trust per player. NEVER exposes the raw number to the client --
-- only the bucketed state (trusted/neutral/suspicious/feared), per DESIGN_BRIEF.md.
-- Trust collapsing into "feared" triggers a checkpoint return, implementing
-- game_mechanics.md rule #2 ("kehilangan terlalu banyak kepercayaan warga akan
-- menyebabkan pemain kembali ke checkpoint sebelumnya").

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Modules = ReplicatedStorage:WaitForChild("Modules")
local GameConfig = require(Modules.GameConfig)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)

local TrustService = {}

local trustByPlayer = {}
local stateByPlayer = {}
local Services

local function stateFor(value)
	for _, tier in ipairs(GameConfig.Trust.Thresholds) do
		if value <= tier.max then
			return tier.state
		end
	end
	return GameConfig.Trust.Thresholds[#GameConfig.Trust.Thresholds].state
end

function TrustService.Init(services)
	Services = services
end

function TrustService.InitPlayer(player, initialTrust)
	local value = initialTrust or GameConfig.Trust.Default
	trustByPlayer[player] = value
	stateByPlayer[player] = stateFor(value)
end

function TrustService.RemovePlayer(player)
	trustByPlayer[player] = nil
	stateByPlayer[player] = nil
end

-- Public: bucketed state only. Safe to expose to UI/other Services.
function TrustService.GetState(player)
	return stateByPlayer[player] or stateFor(GameConfig.Trust.Default)
end

-- Internal use only (other Services deciding gameplay outcomes). Never send to client.
function TrustService.GetNumeric(player)
	return trustByPlayer[player] or GameConfig.Trust.Default
end

function TrustService.Adjust(player, delta, difficulty)
	local current = trustByPlayer[player]
	if not current then
		return
	end

	if delta < 0 and difficulty then
		local tier = GameConfig.Difficulty[difficulty]
		if tier then
			delta = delta * tier.TrustPunishmentMultiplier
		end
	end

	local newValue = math.clamp(current + delta, GameConfig.Trust.Min, GameConfig.Trust.Max)
	trustByPlayer[player] = newValue

	if Services and Services.SaveService then
		Services.SaveService.SetTrustReputation(player, newValue)
	end

	local previousState = stateByPlayer[player]
	local newState = stateFor(newValue)
	if newState ~= previousState then
		stateByPlayer[player] = newState
		RemoteRegistry.Get("Trust/StateChanged"):FireClient(player, { state = newState })

		if newState == "feared" and previousState ~= "feared" and Services and Services.CheckpointService then
			Services.CheckpointService.ReturnToLastCheckpoint(player, "trust_collapsed")
		end
	end
end

return TrustService
]====]
    },
    {
        path = "game.StarterPlayer.StarterPlayerScripts.GameClient.Bootstrap",
        className = "LocalScript",
        content = [====[-- StarterPlayerScripts/GameClient/Bootstrap.client.lua
-- Entry point for the Main Game client. Waits for Remotes to exist, then starts every
-- Controller. Add new Controllers here as they're built (MAIN_GAME_SYSTEM_RULES.md §10).

local ReplicatedStorage = game:GetService("ReplicatedStorage")
ReplicatedStorage:WaitForChild("Modules")
ReplicatedStorage:WaitForChild("Remotes")

local Controllers = script.Parent.Controllers

require(Controllers.HUDController).Start()
require(Controllers.JournalController).Start()
require(Controllers.DialogueController).Start()
require(Controllers.PuzzleController).Start()
require(Controllers.HorrorController).Start()
require(Controllers.CheckpointController).Start()
require(Controllers.AccusationController).Start()
require(Controllers.EndingController).Start()

print("[GameClient] Bootstrap complete.")
]====]
    },
    {
        path = "game.StarterPlayer.StarterPlayerScripts.GameClient.Controllers.AccusationController",
        className = "ModuleScript",
        content = [====[-- StarterPlayerScripts/GameClient/Controllers/AccusationController.lua
-- Suspect picker + confirm step. The Confirm button stays disabled until a suspect is
-- selected, so there's no accidental one-click accusation (per MAIN_GAME_SYSTEM_RULES.md
-- §9 UI inventory notes).

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Modules = ReplicatedStorage:WaitForChild("Modules")
local GameConfig = require(Modules.GameConfig)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)
local UIKit = require(script.Parent.Parent.UI.UIKit)

local AccusationController = {}
local player = Players.LocalPlayer

function AccusationController.Start()
	local gui = UIKit.NewScreenGui("AccusationGui")
	gui.Enabled = false
	gui.Parent = player:WaitForChild("PlayerGui")

	local root = UIKit.NewFrame({
		Name = "Root",
		Parent = gui,
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.fromScale(0.4, 0.55),
	})

	UIKit.NewLabel({
		Name = "Title",
		Parent = root,
		Text = "Siapa pelakunya?",
		Font = UIKit.Font.Heading,
		Position = UDim2.new(0, 10, 0, 10),
		Size = UDim2.new(1, -20, 0, 30),
	})

	local list = Instance.new("Frame")
	list.Name = "ChoiceList"
	list.BackgroundTransparency = 1
	list.Position = UDim2.new(0, 10, 0, 50)
	list.Size = UDim2.new(1, -20, 1, -110)
	list.Parent = root

	local layout = Instance.new("UIListLayout")
	layout.Padding = UDim.new(0, 6)
	layout.Parent = list

	local feedback = UIKit.NewLabel({
		Name = "Feedback",
		Parent = root,
		Position = UDim2.new(0, 10, 1, -70),
		Size = UDim2.new(1, -20, 0, 24),
		TextColor3 = UIKit.Palette.TextMuted,
	})

	local confirmButton = UIKit.NewButton({
		Name = "CloseButton", -- role: confirm/close action
		Parent = root,
		Text = "Konfirmasi Tuduhan",
		AnchorPoint = Vector2.new(0.5, 1),
		Position = UDim2.new(0.5, 0, 1, -10),
		Size = UDim2.new(1, -20, 0, 36),
		BackgroundColor3 = UIKit.Palette.MoonlightBlue,
	})
	confirmButton.Active = false
	confirmButton.AutoButtonColor = false

	local selectedId = nil

	local function refreshConfirmState()
		confirmButton.Active = selectedId ~= nil
		confirmButton.AutoButtonColor = selectedId ~= nil
		confirmButton.BackgroundColor3 = selectedId and UIKit.Palette.FearedRed or UIKit.Palette.MoonlightBlue
	end

	confirmButton.MouseButton1Click:Connect(function()
		if not selectedId then
			return
		end
		RemoteRegistry.Get("Accusation/Submit"):FireServer({ suspectId = selectedId })
	end)

	RemoteRegistry.Get("Accusation/Open").OnClientEvent:Connect(function(data)
		gui.Enabled = true
		selectedId = nil
		feedback.Text = ""
		refreshConfirmState()

		for _, child in ipairs(list:GetChildren()) do
			if child:IsA("GuiObject") then
				child:Destroy()
			end
		end

		for _, suspect in ipairs(data.suspects) do
			local button = UIKit.NewButton({
				Name = "Suspect_" .. suspect.id,
				Parent = list,
				Text = suspect.name,
				Size = UDim2.new(1, 0, 0, 34),
			})
			button.MouseButton1Click:Connect(function()
				selectedId = suspect.id
				for _, sibling in ipairs(list:GetChildren()) do
					if sibling:IsA("TextButton") then
						sibling.BackgroundColor3 = UIKit.Palette.PanelBlue
					end
				end
				button.BackgroundColor3 = UIKit.Palette.LanternOrange
				refreshConfirmState()
			end)
		end
	end)

	RemoteRegistry.Get("Accusation/Result").OnClientEvent:Connect(function(data)
		if data.outcome == "not_enough_clues" then
			feedback.Text = "Kamu butuh lebih banyak bukti sebelum menuduh."
			feedback.TextColor3 = UIKit.Palette.TextMuted
		elseif data.outcome == "wrong" then
			feedback.Text = "Sepertinya bukan dia..."
			feedback.TextColor3 = UIKit.Palette.FearedRed
			gui.Enabled = false
		else
			UIKit.PlaySound(GameConfig.Audio.Kentongan, 0.7)
			gui.Enabled = false
		end
	end)
end

return AccusationController
]====]
    },
    {
        path = "game.StarterPlayer.StarterPlayerScripts.GameClient.Controllers.CheckpointController",
        className = "ModuleScript",
        content = [====[-- StarterPlayerScripts/GameClient/Controllers/CheckpointController.lua
-- Small auto-dismissing toast for checkpoint saves, forced returns (trust collapse /
-- time up), hint unlocks, and generic "locked interactable" notices. Never blocks input.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Modules = ReplicatedStorage:WaitForChild("Modules")
local GameConfig = require(Modules.GameConfig)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)
local UIKit = require(script.Parent.Parent.UI.UIKit)

local CheckpointController = {}
local player = Players.LocalPlayer

local RETURN_REASON_TEXT = {
	trust_collapsed = "Warga sudah tidak mempercayaimu -- kamu dikembalikan ke checkpoint terakhir.",
	time_up = "Waktu ronda habis -- kamu dikembalikan ke checkpoint terakhir.",
	unknown = "Kamu dikembalikan ke checkpoint terakhir.",
}

function CheckpointController.Start()
	local gui = UIKit.NewScreenGui("CheckpointGui")
	gui.Parent = player:WaitForChild("PlayerGui")

	local toast = UIKit.NewFrame({
		Name = "Root",
		Parent = gui,
		AnchorPoint = Vector2.new(0.5, 1),
		Position = UDim2.fromScale(0.5, 0.92),
		Size = UDim2.fromScale(0.32, 0.06),
		Visible = false,
	})

	local label = UIKit.NewLabel({
		Name = "Label",
		Parent = toast,
		Text = "Progres disimpan",
	})

	local function showToast(text, duration)
		label.Text = text
		toast.BackgroundTransparency = 1
		UIKit.FadeIn(toast, 0.15, 0.25)
		task.delay(duration or 2.2, function()
			UIKit.FadeOutAndHide(toast, 0.3)
		end)
	end

	RemoteRegistry.Get("Checkpoint/Saved").OnClientEvent:Connect(function()
		showToast("Progres disimpan")
		UIKit.PlaySound(GameConfig.Audio.Kentongan, 0.5)
	end)

	RemoteRegistry.Get("Checkpoint/Returned").OnClientEvent:Connect(function(data)
		showToast(RETURN_REASON_TEXT[data.reason] or RETURN_REASON_TEXT.unknown, 3.5)
		UIKit.PlaySound(GameConfig.Audio.Kentongan, 0.6)
	end)

	RemoteRegistry.Get("Checkpoint/HintUnlocked").OnClientEvent:Connect(function()
		showToast("Petunjuk baru tersedia di jurnal")
	end)

	RemoteRegistry.Get("Interaction/Locked").OnClientEvent:Connect(function()
		showToast("Terkunci -- ada yang perlu ditemukan dulu.", 1.8)
	end)

	RemoteRegistry.Get("Night/TimeUp").OnClientEvent:Connect(function(data)
		if data.questCompleted then
			showToast("Tugas ronda malam ini selesai!", 2.5)
		end
		-- The "not completed" case is already covered by the Checkpoint/Returned toast
		-- that fires right after this (see NightTimerService).
	end)
end

return CheckpointController
]====]
    },
    {
        path = "game.StarterPlayer.StarterPlayerScripts.GameClient.Controllers.DialogueController",
        className = "ModuleScript",
        content = [====[-- StarterPlayerScripts/GameClient/Controllers/DialogueController.lua
-- Renders whatever node DialogueService sends. Locked choices are rendered using the
-- `locked`/`lockedReason` fields the server already computed -- this Controller never
-- infers lock state itself (ROBLOX_UI_SKILL.md §6).

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Modules = ReplicatedStorage:WaitForChild("Modules")
local RemoteRegistry = require(Modules.Net.RemoteRegistry)
local UIKit = require(script.Parent.Parent.UI.UIKit)

local DialogueController = {}
local player = Players.LocalPlayer

function DialogueController.Start()
	local gui = UIKit.NewScreenGui("DialogueGui")
	gui.Enabled = false
	gui.Parent = player:WaitForChild("PlayerGui")

	local root = UIKit.NewFrame({
		Name = "Root",
		Parent = gui,
		AnchorPoint = Vector2.new(0.5, 1),
		Position = UDim2.fromScale(0.5, 0.95),
		Size = UDim2.fromScale(0.6, 0.32),
	})

	local npcName = UIKit.NewLabel({
		Name = "Title",
		Parent = root,
		Font = UIKit.Font.Heading,
		Position = UDim2.new(0, 10, 0, 5),
		Size = UDim2.new(1, -20, 0, 28),
	})

	local bodyText = UIKit.NewLabel({
		Name = "Body",
		Parent = root,
		Font = UIKit.Font.Narrative,
		Position = UDim2.new(0, 10, 0, 38),
		Size = UDim2.new(1, -20, 0, 60),
		TextXAlignment = Enum.TextXAlignment.Left,
		TextYAlignment = Enum.TextYAlignment.Top,
		TextWrapped = true,
	})

	local choicesHolder = Instance.new("Frame")
	choicesHolder.Name = "ChoiceList"
	choicesHolder.BackgroundTransparency = 1
	choicesHolder.Position = UDim2.new(0, 10, 0, 102)
	choicesHolder.Size = UDim2.new(1, -20, 1, -112)
	choicesHolder.Parent = root

	local layout = Instance.new("UIListLayout")
	layout.Padding = UDim.new(0, 4)
	layout.Parent = choicesHolder

	local currentNodeId = nil

	local function render(data)
		gui.Enabled = true
		currentNodeId = data.nodeId
		npcName.Text = data.npcName
		bodyText.Text = data.text

		for _, child in ipairs(choicesHolder:GetChildren()) do
			if child:IsA("GuiObject") then
				child:Destroy()
			end
		end

		for _, choice in ipairs(data.choices) do
			local button = UIKit.NewButton({
				Name = "Choice_" .. choice.id,
				Parent = choicesHolder,
				Text = choice.locked and (choice.text .. "  🔒") or choice.text,
				Size = UDim2.new(1, 0, 0, 30),
				BackgroundColor3 = choice.locked and UIKit.Palette.MoonlightBlue or UIKit.Palette.PanelBlue,
				TextColor3 = choice.locked and UIKit.Palette.TextMuted or UIKit.Palette.TextLight,
			})
			button.AutoButtonColor = not choice.locked
			button.Active = not choice.locked

			button.MouseButton1Click:Connect(function()
				if choice.locked then
					return
				end
				RemoteRegistry.Get("Dialogue/Choose"):FireServer({
					nodeId = currentNodeId,
					choiceId = choice.id,
				})
			end)
		end

		if #data.choices == 0 then
			task.delay(2.5, function()
				if currentNodeId == data.nodeId then
					gui.Enabled = false
				end
			end)
		end
	end

	RemoteRegistry.Get("Dialogue/Node").OnClientEvent:Connect(render)
end

return DialogueController
]====]
    },
    {
        path = "game.StarterPlayer.StarterPlayerScripts.GameClient.Controllers.EndingController",
        className = "ModuleScript",
        content = [====[-- StarterPlayerScripts/GameClient/Controllers/EndingController.lua
-- Full-screen ending display. The server only ever sends an `endingId`; this Controller
-- resolves the Title/Text by requiring the shared NarrativeData module directly (it's
-- replicated, read-only reference data -- not a gameplay decision) rather than the
-- server pushing full text over the Remote every time.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Modules = ReplicatedStorage:WaitForChild("Modules")
local NarrativeData = require(Modules.NarrativeData)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)
local UIKit = require(script.Parent.Parent.UI.UIKit)

local EndingController = {}
local player = Players.LocalPlayer

function EndingController.Start()
	local gui = UIKit.NewScreenGui("EndingGui")
	gui.Enabled = false
	gui.DisplayOrder = 50
	gui.Parent = player:WaitForChild("PlayerGui")

	local root = UIKit.NewFrame({
		Name = "Root",
		Parent = gui,
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 0,
		BackgroundColor3 = UIKit.Palette.MoonlightBlue,
		CornerRadius = UDim.new(0, 0),
	})

	local title = UIKit.NewLabel({
		Name = "Title",
		Parent = root,
		AnchorPoint = Vector2.new(0.5, 0),
		Position = UDim2.fromScale(0.5, 0.3),
		Size = UDim2.fromScale(0.6, 0.08),
		Font = UIKit.Font.Heading,
	})

	local body = UIKit.NewLabel({
		Name = "Body",
		Parent = root,
		AnchorPoint = Vector2.new(0.5, 0),
		Position = UDim2.fromScale(0.5, 0.42),
		Size = UDim2.fromScale(0.5, 0.2),
		Font = UIKit.Font.Narrative,
		TextColor3 = UIKit.Palette.TextMuted,
		TextWrapped = true,
	})

	local closeButton = UIKit.NewButton({
		Name = "CloseButton",
		Parent = root,
		AnchorPoint = Vector2.new(0.5, 0),
		Position = UDim2.fromScale(0.5, 0.68),
		Size = UDim2.fromScale(0.2, 0.06),
		Text = "Lanjutkan",
	})
	closeButton.MouseButton1Click:Connect(function()
		gui.Enabled = false
	end)

	RemoteRegistry.Get("Accusation/Result").OnClientEvent:Connect(function(data)
		if not data.endingId then
			return
		end
		local ending = NarrativeData.Endings[data.endingId]
		if not ending then
			warn("[EndingController] Unknown endingId:", data.endingId)
			return
		end
		title.Text = ending.Title
		body.Text = ending.Text
		gui.Enabled = true
	end)
end

return EndingController
]====]
    },
    {
        path = "game.StarterPlayer.StarterPlayerScripts.GameClient.Controllers.HorrorController",
        className = "ModuleScript",
        content = [====[-- StarterPlayerScripts/GameClient/Controllers/HorrorController.lua
-- Purely cosmetic reaction to Horror/Event and Entity/Sighted. Never sets Modal = true
-- and never intercepts clicks/ProximityPrompts (ROBLOX_UI_SKILL.md §2). Entity sightings
-- optionally carry a flavor name (setan gundul / methek) from NarrativeData.EntityNames.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")

local Modules = ReplicatedStorage:WaitForChild("Modules")
local GameConfig = require(Modules.GameConfig)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)
local UIKit = require(script.Parent.Parent.UI.UIKit)

local HorrorController = {}
local player = Players.LocalPlayer

local WHISPER_LINES = {
	"...ada yang mengawasi...",
	"...jangan percaya semua yang kau lihat...",
	"...belum selesai...",
}

function HorrorController.Start()
	local gui = UIKit.NewScreenGui("HorrorGui")
	gui.DisplayOrder = 100
	gui.Parent = player:WaitForChild("PlayerGui")

	local vignette = Instance.new("Frame")
	vignette.Name = "Root"
	vignette.Size = UDim2.fromScale(1, 1)
	vignette.BackgroundColor3 = Color3.new(0, 0, 0)
	vignette.BackgroundTransparency = 1
	vignette.BorderSizePixel = 0
	vignette.Active = false -- never intercepts input
	vignette.Parent = gui

	local subtitle = UIKit.NewLabel({
		Name = "Subtitle",
		Parent = gui,
		AnchorPoint = Vector2.new(0.5, 1),
		Position = UDim2.fromScale(0.5, 0.85),
		Size = UDim2.fromScale(0.5, 0.06),
		Font = UIKit.Font.Narrative,
		TextColor3 = UIKit.Palette.TextMuted,
	})
	subtitle.Text = ""

	local function playVignettePulse()
		local tweenIn = TweenService:Create(
			vignette,
			TweenInfo.new(0.6, Enum.EasingStyle.Sine, Enum.EasingDirection.Out),
			{ BackgroundTransparency = 0.75 }
		)
		tweenIn:Play()
		tweenIn.Completed:Connect(function()
			TweenService:Create(
				vignette,
				TweenInfo.new(1.2, Enum.EasingStyle.Sine, Enum.EasingDirection.In),
				{ BackgroundTransparency = 1 }
			):Play()
		end)
	end

	local function showWhisper(line)
		subtitle.Text = line
		TweenService:Create(subtitle, TweenInfo.new(0.4), { TextTransparency = 0 }):Play()
		task.delay(3, function()
			TweenService:Create(subtitle, TweenInfo.new(0.6), { TextTransparency = 1 }):Play()
		end)
	end

	RemoteRegistry.Get("Horror/Event").OnClientEvent:Connect(function(data)
		if data.eventType == "whisper" then
			showWhisper(WHISPER_LINES[math.random(1, #WHISPER_LINES)])
			UIKit.PlaySound(GameConfig.Audio.HorrorWhisper, 0.4)
		else
			playVignettePulse()
		end
	end)

	RemoteRegistry.Get("Entity/Sighted").OnClientEvent:Connect(function(data)
		playVignettePulse()
		UIKit.PlaySound(GameConfig.Audio.HorrorWhisper, 0.4)
		if data.entityHint then
			showWhisper(string.format("...%s bergerak di kegelapan...", data.entityHint))
		else
			showWhisper("...sesuatu bergerak di kegelapan...")
		end
	end)
end

return HorrorController
]====]
    },
    {
        path = "game.StarterPlayer.StarterPlayerScripts.GameClient.Controllers.HUDController",
        className = "ModuleScript",
        content = [====[-- StarterPlayerScripts/GameClient/Controllers/HUDController.lua
-- Always-visible HUD: objective tracker (carried + deposited jimpitan), trust indicator,
-- night countdown clock, and a simple XZ-projection minimap blip. The minimap background
-- is a plain panel for now -- swap in a real top-down map ImageLabel once the
-- environment team exports one (see README_IMPLEMENTATION.md). Coordinate math assumes
-- Workspace.Map is centered on world origin (0,0,0), per MAP_LEVEL_DESIGN_GUIDE.md's
-- 2048x2048 baseplate -- adjust the offset here if WorldData places it elsewhere.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")

local Modules = ReplicatedStorage:WaitForChild("Modules")
local GameConfig = require(Modules.GameConfig)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)

local UIKit = require(script.Parent.Parent.UI.UIKit)

local HUDController = {}
local player = Players.LocalPlayer

local TRUST_DISPLAY = {
	trusted = { text = "\240\159\143\174 Dipercaya", color = Color3.fromRGB(120, 200, 140) },
	neutral = { text = "\240\159\143\174 Netral", color = nil },
	suspicious = { text = "\240\159\143\174 Dicurigai", color = Color3.fromRGB(210, 150, 60) },
	feared = { text = "\240\159\143\174 Ditakuti", color = nil },
}

local function formatClock(seconds)
	local m = math.floor(seconds / 60)
	local s = seconds % 60
	return string.format("%02d:%02d", m, s)
end

function HUDController.Start()
	TRUST_DISPLAY.neutral.color = UIKit.Palette.LanternOrange
	TRUST_DISPLAY.feared.color = UIKit.Palette.FearedRed

	local gui = UIKit.NewScreenGui("HUDGui")
	gui.Parent = player:WaitForChild("PlayerGui")

	-- Objective tracker (top-left)
	local objectiveFrame = UIKit.NewFrame({
		Name = "Objective",
		Parent = gui,
		Position = UDim2.fromScale(0.02, 0.03),
		Size = UDim2.fromScale(0.3, 0.09),
	})
	local objectiveLabel = UIKit.NewLabel({
		Name = "Label",
		Parent = objectiveFrame,
		Position = UDim2.new(0, 8, 0, 2),
		Size = UDim2.new(1, -16, 0.55, 0),
		Text = "Kumpulkan jimpitan (0/0)",
	})
	local carriedLabel = UIKit.NewLabel({
		Name = "Carried",
		Parent = objectiveFrame,
		Position = UDim2.new(0, 8, 0.55, 0),
		Size = UDim2.new(1, -16, 0.4, 0),
		Text = "",
		TextColor3 = UIKit.Palette.TextMuted,
		MaxTextSize = 16,
	})

	-- Night clock (top-center) -- counts down "waktu ronda" (game_mechanics.md rule #1)
	local clockFrame = UIKit.NewFrame({
		Name = "NightClock",
		Parent = gui,
		AnchorPoint = Vector2.new(0.5, 0),
		Position = UDim2.fromScale(0.5, 0.03),
		Size = UDim2.fromScale(0.12, 0.06),
	})
	local clockLabel = UIKit.NewLabel({
		Name = "Label",
		Parent = clockFrame,
		Text = "--:--",
		Font = UIKit.Font.Heading,
		TextXAlignment = Enum.TextXAlignment.Center,
	})

	-- Trust indicator (top-right)
	local trustFrame = UIKit.NewFrame({
		Name = "Trust",
		Parent = gui,
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.fromScale(0.98, 0.03),
		Size = UDim2.fromScale(0.2, 0.07),
	})
	local trustLabel = UIKit.NewLabel({
		Name = "Label",
		Parent = trustFrame,
		Text = TRUST_DISPLAY.neutral.text,
		TextColor3 = TRUST_DISPLAY.neutral.color,
		Font = UIKit.Font.Heading,
	})

	-- Minimap (bottom-right)
	local minimapFrame = UIKit.NewFrame({
		Name = "Minimap",
		Parent = gui,
		AnchorPoint = Vector2.new(1, 1),
		Position = UDim2.fromScale(0.98, 0.97),
		Size = UDim2.fromScale(0.16, 0.28),
		BackgroundTransparency = 0.3,
	})

	local blip = Instance.new("Frame")
	blip.Name = "PlayerBlip"
	blip.AnchorPoint = Vector2.new(0.5, 0.5)
	blip.Size = UDim2.fromOffset(8, 8)
	blip.BackgroundColor3 = UIKit.Palette.LanternOrange
	blip.BorderSizePixel = 0
	blip.Parent = minimapFrame
	local blipCorner = Instance.new("UICorner")
	blipCorner.CornerRadius = UDim.new(1, 0)
	blipCorner.Parent = blip

	RunService.Heartbeat:Connect(function()
		local character = player.Character
		local root = character and character:FindFirstChild("HumanoidRootPart")
		if not root then
			return
		end
		local half = GameConfig.World.MAP_HALF_SIZE
		local nx = math.clamp((root.Position.X + half) / (half * 2), 0, 1)
		local nz = math.clamp((root.Position.Z + half) / (half * 2), 0, 1)
		blip.Position = UDim2.fromScale(nx, nz)
	end)

	RemoteRegistry.Get("Objective/StateChanged").OnClientEvent:Connect(function(data)
		objectiveLabel.Text = string.format("%s (%d/%d)", data.label, data.progress, data.target)
		carriedLabel.Text = (data.carried or 0) > 0
			and string.format("Dibawa: %d (belum disetor)", data.carried)
			or ""
	end)

	RemoteRegistry.Get("Trust/StateChanged").OnClientEvent:Connect(function(data)
		local display = TRUST_DISPLAY[data.state] or TRUST_DISPLAY.neutral
		trustLabel.Text = display.text
		trustLabel.TextColor3 = display.color
	end)

	RemoteRegistry.Get("Night/TimeUpdated").OnClientEvent:Connect(function(data)
		clockLabel.Text = formatClock(data.secondsRemaining)
		clockLabel.TextColor3 = data.secondsRemaining <= 60 and UIKit.Palette.FearedRed or UIKit.Palette.TextLight
	end)
end

return HUDController
]====]
    },
    {
        path = "game.StarterPlayer.StarterPlayerScripts.GameClient.Controllers.JournalController",
        className = "ModuleScript",
        content = [====[-- StarterPlayerScripts/GameClient/Controllers/JournalController.lua
-- Clue journal. Toggled with the J key. Clones one template Label per clue entry
-- (ROBLOX_UI_SKILL.md §5 -- never hand-place duplicates).

local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Modules = ReplicatedStorage:WaitForChild("Modules")
local GameConfig = require(Modules.GameConfig)
local RemoteRegistry = require(Modules.Net.RemoteRegistry)
local UIKit = require(script.Parent.Parent.UI.UIKit)

local JournalController = {}
local player = Players.LocalPlayer

function JournalController.Start()
	local gui = UIKit.NewScreenGui("JournalGui")
	gui.Enabled = false
	gui.Parent = player:WaitForChild("PlayerGui")

	local root = UIKit.NewFrame({
		Name = "Root",
		Parent = gui,
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.fromScale(0.4, 0.6),
		BackgroundTransparency = 0.05,
	})

	UIKit.NewLabel({
		Name = "Title",
		Parent = root,
		Text = "Jurnal Petunjuk",
		Font = UIKit.Font.Heading,
		Position = UDim2.new(0, 10, 0, 5),
		Size = UDim2.new(1, -20, 0, 34),
	})

	local list = Instance.new("ScrollingFrame")
	list.Name = "ChoiceList"
	list.BackgroundTransparency = 1
	list.BorderSizePixel = 0
	list.Position = UDim2.new(0, 10, 0, 50)
	list.Size = UDim2.new(1, -20, 1, -60)
	list.CanvasSize = UDim2.new(0, 0, 0, 0)
	list.AutomaticCanvasSize = Enum.AutomaticSize.Y
	list.ScrollBarThickness = 6
	list.Parent = root

	local layout = Instance.new("UIListLayout")
	layout.Padding = UDim.new(0, 6)
	layout.Parent = list

	local template = UIKit.NewLabel({
		Name = "EntryTemplate",
		Parent = nil,
		Size = UDim2.new(1, 0, 0, 40),
		TextXAlignment = Enum.TextXAlignment.Left,
		TextYAlignment = Enum.TextYAlignment.Top,
		TextWrapped = true,
	})

	UserInputService.InputBegan:Connect(function(input, processed)
		if processed then
			return
		end
		if input.KeyCode == Enum.KeyCode.J then
			gui.Enabled = not gui.Enabled
		end
	end)

	RemoteRegistry.Get("Investigation/ClueAdded").OnClientEvent:Connect(function(data)
		local entry = template:Clone()
		entry.Name = "Entry_" .. data.clueId
		entry.Text = "\226\128\162 " .. data.text
		entry.Parent = list
		UIKit.PlaySound(GameConfig.Audio.ClueFound, 0.5)
	end)
end

return JournalController
]====]
    },
    {
        path = "game.StarterPlayer.StarterPlayerScripts.GameClient.Controllers.PuzzleController",
        className = "ModuleScript",
        content = [====[-- StarterPlayerScripts/GameClient/Controllers/PuzzleController.lua
-- Generic overlay for PuzzleService's multiple-choice "observation" puzzle type.
-- Adding a new PuzzleId on the server needs zero changes here -- this Controller only
-- ever renders whatever `question`/`options` Puzzle/Data sends.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Modules = ReplicatedStorage:WaitForChild("Modules")
local RemoteRegistry = require(Modules.Net.RemoteRegistry)
local UIKit = require(script.Parent.Parent.UI.UIKit)

local PuzzleController = {}
local player = Players.LocalPlayer

function PuzzleController.Start()
	local gui = UIKit.NewScreenGui("PuzzleGui")
	gui.Enabled = false
	gui.Parent = player:WaitForChild("PlayerGui")

	local root = UIKit.NewFrame({
		Name = "Root",
		Parent = gui,
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.fromScale(0.45, 0.45),
	})

	local question = UIKit.NewLabel({
		Name = "Title",
		Parent = root,
		Font = UIKit.Font.Heading,
		Position = UDim2.new(0, 10, 0, 10),
		Size = UDim2.new(1, -20, 0, 60),
		TextWrapped = true,
	})

	local optionsHolder = Instance.new("Frame")
	optionsHolder.Name = "ChoiceList"
	optionsHolder.BackgroundTransparency = 1
	optionsHolder.Position = UDim2.new(0, 10, 0, 80)
	optionsHolder.Size = UDim2.new(1, -20, 1, -140)
	optionsHolder.Parent = root

	local layout = Instance.new("UIListLayout")
	layout.Padding = UDim.new(0, 6)
	layout.Parent = optionsHolder

	local feedback = UIKit.NewLabel({
		Name = "Feedback",
		Parent = root,
		Position = UDim2.new(0, 10, 1, -50),
		Size = UDim2.new(1, -20, 0, 40),
		TextColor3 = UIKit.Palette.LanternOrange,
	})

	local hintBadge = UIKit.NewLabel({
		Name = "HintBadge",
		Parent = root,
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.new(1, -10, 0, 10),
		Size = UDim2.fromOffset(28, 28),
		Text = "💡",
		Visible = false,
	})

	local currentPuzzleId = nil

	RemoteRegistry.Get("Puzzle/Data").OnClientEvent:Connect(function(data)
		gui.Enabled = true
		currentPuzzleId = data.puzzleId
		question.Text = data.question
		feedback.Text = ""

		for _, child in ipairs(optionsHolder:GetChildren()) do
			if child:IsA("GuiObject") then
				child:Destroy()
			end
		end

		for _, option in ipairs(data.options) do
			local button = UIKit.NewButton({
				Name = "Option_" .. option.id,
				Parent = optionsHolder,
				Text = option.text,
				Size = UDim2.new(1, 0, 0, 34),
			})
			button.MouseButton1Click:Connect(function()
				RemoteRegistry.Get("Puzzle/Submit"):FireServer({
					puzzleId = currentPuzzleId,
					answer = option.id,
				})
			end)
		end
	end)

	RemoteRegistry.Get("Puzzle/Result").OnClientEvent:Connect(function(data)
		if data.success then
			feedback.Text = "Benar! Petunjuk baru ditambahkan ke jurnal."
			feedback.TextColor3 = Color3.fromRGB(120, 200, 140)
		else
			feedback.Text = "Sepertinya bukan itu. Coba amati lagi lain kali."
			feedback.TextColor3 = UIKit.Palette.FearedRed
		end
		task.delay(1.5, function()
			gui.Enabled = false
		end)
	end)

	RemoteRegistry.Get("Checkpoint/HintUnlocked").OnClientEvent:Connect(function()
		hintBadge.Visible = true
	end)
end

return PuzzleController
]====]
    },
    {
        path = "game.StarterPlayer.StarterPlayerScripts.GameClient.UI.UIKit",
        className = "ModuleScript",
        content = [====[-- StarterPlayerScripts/GameClient/UI/UIKit.lua
-- Shared instance-builder + style helpers, implementing ROBLOX_UI_SKILL.md §1-4.
-- Every Controller should build its ScreenGui through these helpers rather than
-- hand-rolling Instance.new calls, so palette/typography/motion stay consistent.

local TweenService = game:GetService("TweenService")
local SoundService = game:GetService("SoundService")

local UIKit = {}

-- §3 Visual style guide -------------------------------------------------------------
UIKit.Palette = {
	LanternOrange = Color3.fromRGB(232, 168, 85),
	MoonlightBlue = Color3.fromRGB(28, 34, 46),
	PanelBlue = Color3.fromRGB(20, 24, 33),
	FearedRed = Color3.fromRGB(150, 40, 40),
	TextLight = Color3.fromRGB(235, 230, 220),
	TextMuted = Color3.fromRGB(160, 160, 165),
}

-- TODO(art): swap Narrative for a licensed rustic/hand-written font asset once one is
-- picked; Enum.Font.Cartoon is a placeholder that is at least NOT a generic UI sans.
UIKit.Font = {
	Narrative = Enum.Font.Cartoon,
	Body = Enum.Font.Gotham,
	Heading = Enum.Font.GothamBold,
}

function UIKit.NewScreenGui(name)
	local gui = Instance.new("ScreenGui")
	gui.Name = name
	gui.ResetOnSpawn = false
	gui.Enabled = true
	return gui
end

function UIKit.NewFrame(props)
	local frame = Instance.new("Frame")
	frame.Name = props.Name or "Frame"
	frame.BackgroundColor3 = props.BackgroundColor3 or UIKit.Palette.PanelBlue
	frame.BackgroundTransparency = props.BackgroundTransparency or 0.15
	frame.BorderSizePixel = 0
	frame.AnchorPoint = props.AnchorPoint or Vector2.new(0, 0)
	frame.Position = props.Position or UDim2.fromScale(0, 0)
	frame.Size = props.Size or UDim2.fromScale(0.2, 0.1)
	frame.Visible = props.Visible ~= false
	frame.Parent = props.Parent

	local corner = Instance.new("UICorner")
	corner.CornerRadius = props.CornerRadius or UDim.new(0, 8)
	corner.Parent = frame

	return frame
end

function UIKit.NewLabel(props)
	local label = Instance.new("TextLabel")
	label.Name = props.Name or "Label"
	label.BackgroundTransparency = 1
	label.Font = props.Font or UIKit.Font.Body
	label.TextColor3 = props.TextColor3 or UIKit.Palette.TextLight
	label.TextScaled = true
	label.TextWrapped = props.TextWrapped or false
	label.Text = props.Text or ""
	label.TextXAlignment = props.TextXAlignment or Enum.TextXAlignment.Left
	label.TextYAlignment = props.TextYAlignment or Enum.TextYAlignment.Center
	label.AnchorPoint = props.AnchorPoint or Vector2.new(0, 0)
	label.Position = props.Position or UDim2.fromScale(0, 0)
	label.Size = props.Size or UDim2.fromScale(1, 1)
	label.Visible = props.Visible ~= false
	label.Parent = props.Parent

	local constraint = Instance.new("UITextSizeConstraint")
	constraint.MaxTextSize = props.MaxTextSize or 24
	constraint.MinTextSize = props.MinTextSize or 10
	constraint.Parent = label

	return label
end

function UIKit.NewButton(props)
	local button = Instance.new("TextButton")
	button.Name = props.Name or "Button"
	button.BackgroundColor3 = props.BackgroundColor3 or UIKit.Palette.PanelBlue
	button.AutoButtonColor = true
	button.BorderSizePixel = 0
	button.Font = props.Font or UIKit.Font.Body
	button.TextColor3 = props.TextColor3 or UIKit.Palette.TextLight
	button.TextScaled = true
	button.Text = props.Text or ""
	button.AnchorPoint = props.AnchorPoint or Vector2.new(0, 0)
	button.Position = props.Position or UDim2.fromScale(0, 0)
	button.Size = props.Size or UDim2.fromScale(1, 0.2)
	button.Parent = props.Parent

	local corner = Instance.new("UICorner")
	corner.CornerRadius = UDim.new(0, 6)
	corner.Parent = button

	local constraint = Instance.new("UITextSizeConstraint")
	constraint.MaxTextSize = 22
	constraint.MinTextSize = 10
	constraint.Parent = button

	return button
end

-- §4 Motion & feedback ----------------------------------------------------------------
-- Standard show/hide tween: Quad/Out, 0.2-0.35s, per ROBLOX_UI_SKILL.md.

function UIKit.FadeIn(guiObject, targetTransparency, duration)
	guiObject.Visible = true
	local tween = TweenService:Create(
		guiObject,
		TweenInfo.new(duration or 0.25, Enum.EasingStyle.Quad, Enum.EasingDirection.Out),
		{ BackgroundTransparency = targetTransparency or 0.15 }
	)
	tween:Play()
	return tween
end

function UIKit.FadeOutAndHide(guiObject, duration)
	local tween = TweenService:Create(
		guiObject,
		TweenInfo.new(duration or 0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.Out),
		{ BackgroundTransparency = 1 }
	)
	tween:Play()
	tween.Completed:Connect(function()
		guiObject.Visible = false
	end)
	return tween
end

-- Kentongan / whisper / clue-found sound cues -----------------------------------------
-- No-ops on the rbxassetid://0 placeholders in GameConfig.Audio, so every Controller
-- can call this unconditionally -- it starts working the instant real asset ids land.
function UIKit.PlaySound(soundId, volume)
	if not soundId or soundId == "rbxassetid://0" then
		return
	end
	local sound = Instance.new("Sound")
	sound.SoundId = soundId
	sound.Volume = volume or 0.6
	sound.Parent = SoundService
	sound:Play()
	sound.Ended:Once(function()
		sound:Destroy()
	end)
end

return UIKit
]====]
    },
    {
        path = "game.ReplicatedStorage.Modules.GameConfig",
        className = "ModuleScript",
        content = [====[-- ReplicatedStorage/Modules/GameConfig.lua
-- Single source of numeric/config truth for the Main Game place.
-- See docs/MAIN_GAME_SYSTEM_RULES.md §5-7 for the design rationale behind these values.

local GameConfig = {}

GameConfig.World = {
	MAP_SIZE = 2048,
	MAP_HALF_SIZE = 1024,
}

GameConfig.Difficulty = {
	Easy = {
		TrustPunishmentMultiplier = 1,
		ClueAmbiguity = "clear",
		HorrorFrequency = "low",
		CulpritLayers = 1,
		CheckpointDensity = "normal",
		JimpitanQuota = 8,
	},
	Medium = {
		TrustPunishmentMultiplier = 1.5,
		ClueAmbiguity = "semi",
		HorrorFrequency = "medium",
		CulpritLayers = 1, -- branches to human OR pesugihan, not both
		CheckpointDensity = "normal",
		JimpitanQuota = 10,
	},
	Hard = {
		TrustPunishmentMultiplier = 2,
		ClueAmbiguity = "ambiguous",
		HorrorFrequency = "high",
		CulpritLayers = 2, -- must resolve both human AND pesugihan
		CheckpointDensity = "high",
		JimpitanQuota = 12,
	},
}

-- Min/max seconds between HorrorService/EntityAIService events, keyed by HorrorFrequency.
GameConfig.HorrorIntervalSeconds = {
	low = { min = 90, max = 150 },
	medium = { min = 55, max = 100 },
	high = { min = 30, max = 65 },
}

-- Per-level "waktu ronda" countdown, per game_mechanics.md rule #1. Pacing follows
-- GAME_LAVEL.md: Easy is slow/adaptive, Hard is "cepat, intens, dan konstan".
GameConfig.Night = {
	DurationSeconds = {
		Easy = 600,
		Medium = 480,
		Hard = 360,
	},
	BroadcastIntervalSeconds = 5,
}

GameConfig.Trust = {
	Default = 50,
	Min = 0,
	Max = 100,
	-- Bucketed thresholds -> public state. Never expose the raw numeric value to clients.
	Thresholds = {
		{ state = "feared", max = 20 },
		{ state = "suspicious", max = 45 },
		{ state = "neutral", max = 70 },
		{ state = "trusted", max = 100 },
	},
	-- Base deltas; negative deltas are multiplied by Difficulty.TrustPunishmentMultiplier.
	Delta = {
		CorrectClueShared = 4,
		HelpfulChoice = 3,
		WrongAccusationOfNPC = -15,
		FalseAccusationPublic = -10,
		IgnoredWarga = -2,
	},
}

GameConfig.Investigation = {
	MinCluesForAccusation = 3,
	HintUnlockAfterFailures = 3, -- game_mechanics.md rule #9
}

GameConfig.Ending = {
	Easy = "EasySolved",
	MediumHuman = "MediumHuman",
	MediumPesugihan = "MediumPesugihan",
	HardFull = "HardFull",
	HardPartial = "HardPartial",
}

-- TODO(audio): replace with final asset ids once PUBLISHING.md §7 step 4 is done.
-- Wiring is already live (Kentongan on checkpoint save/return + accusation resolve,
-- HorrorWhisper on horror/entity events, ClueFound on new journal entries) -- these
-- start playing automatically the moment real ids are filled in, no code changes needed.
GameConfig.Audio = {
	Kentongan = "rbxassetid://0",
	HorrorWhisper = "rbxassetid://0",
	ClueFound = "rbxassetid://0",
}

GameConfig.SaveService = {
	DataStoreName = "JimpitanMainProfile_v1",
	AutoSaveIntervalSeconds = 120,
}

return GameConfig
]====]
    },
    {
        path = "game.ReplicatedStorage.Modules.NarrativeData",
        className = "ModuleScript",
        content = [====[-- ReplicatedStorage/Modules/NarrativeData.lua
-- Data-driven narrative content. Client is allowed to require this module directly
-- (it's shared, not server-only) to resolve Ending/Hint display text locally --
-- Services only ever send ids over Remotes, never hardcoded text.
--
-- TODO(narrative): this currently implements ONE full NPC (Pak RT, easy-mode intro
-- branch) as a working example of the Requires/TrustDelta/locked pattern. Extend NPCs /
-- Nodes with the rest of game_naratif.md's Medium/Hard conversations following the same
-- shape -- DialogueService does not need any code changes to support more content.

local GameConfig = require(script.Parent.GameConfig)

local NarrativeData = {}

NarrativeData.NPCs = {
	pak_rt = {
		DisplayName = "Pak RT",
		StartNode = "intro",
		Nodes = {
			intro = {
				Text = "Malam ini kamu mulai ronda. Jangan lupa ambil jimpitan di setiap rumah. "
					.. "Kalau ada kejanggalan, segera lapor.",
				Choices = {
					{ Id = "siap", Text = "Siap, Pak.", Next = "briefing" },
				},
			},
			briefing = {
				Text = "Bagaimana ronda kemarin?",
				Choices = {
					{ Id = "aman", Text = "Aman, Pak.", Next = "continue_night" },
					{
						Id = "report_missing",
						Text = "Pak, uang di pos ronda hilang.",
						Next = "missing_money",
						Requires = { ClueId = "missing_money_clue" },
						-- Honesty about the missing money is rewarded, per
						-- game_mechanics.md's Player Actions table ("Dialogue Choice ...
						-- mempengaruhi tingkat kepercayaan warga"). This is the working
						-- example of the TrustDelta hook -- add it to any other choice
						-- the narrative team wants to move trust.
						TrustDelta = GameConfig.Trust.Delta.HelpfulChoice,
					},
				},
			},
			continue_night = {
				Text = "Bagus. Lanjutkan malam ini.",
				Choices = {},
			},
			missing_money = {
				Text = "Hilang? Coba kamu selidiki dulu sebelum kita simpulkan macam-macam.",
				Choices = {
					{
						Id = "ask_suspect",
						Text = "Pak, menurut Bapak siapa yang mencurigakan?",
						Next = "hint_suspect",
						Requires = { Trust = "neutral" },
					},
				},
			},
			hint_suspect = {
				Text = "Saya tidak mau menuduh sembarangan. Cari bukti dulu, baru bicara ke saya lagi.",
				Choices = {},
			},
		},
	},
}

-- Suspect list shown on the Accusation Board. `eligibleRoles` is what this suspect COULD
-- be cast as if the random case generator picks them -- it is NOT the actual answer.
-- The real per-playthrough solution is decided by CaseGenerationService, not here (see
-- that Service for why: the same static suspect->culprit mapping every game would make
-- every playthrough identical, which the team explicitly did not want).
-- TODO(narrative): replace with the final suspect roster + NPCIds once environment art
-- assigns real names to houses 01-08. Keep at least 2-3 eligible suspects per role so
-- randomization has something to pick from.
NarrativeData.Suspects = {
	{ id = "warga_2", name = "Warga Rumah 02", eligibleRoles = {} }, -- permanent decoy, never guilty
	{ id = "warga_4", name = "Warga Rumah 04", eligibleRoles = { "human" } },
	{ id = "warga_5", name = "Warga Rumah 05", eligibleRoles = { "human" } },
	{ id = "orang_luar", name = "Orang Tak Dikenal", eligibleRoles = { "human" } },
	{ id = "warga_7", name = "Warga Rumah 07 (dekat Sumur)", eligibleRoles = { "pesugihan" } },
	{ id = "warga_8", name = "Warga Rumah 08 (dekat Sumur)", eligibleRoles = { "pesugihan" } },
}

NarrativeData.Endings = {
	EasySolved = {
		Title = "Desa Kembali Aman",
		Text = "Kamu berhasil menemukan pelaku pencurian dari kalangan warga. Pak RT berterima "
			.. "kasih, dan desa kembali tenang -- untuk sementara.",
	},
	MediumHuman = {
		Title = "Pelakunya Orang Luar",
		Text = "Kamu mengungkap bahwa pencurian dilakukan oleh orang luar desa. Warga lega, tapi "
			.. "sebagian bertanya-tanya apakah benar-benar sudah berakhir.",
	},
	MediumPesugihan = {
		Title = "Praktik Pesugihan Terungkap",
		Text = "Kamu menemukan bahwa hilangnya uang berkaitan dengan praktik pesugihan salah satu "
			.. "warga. Desa terguncang oleh kebenaran ini.",
	},
	HardFull = {
		Title = "Kebenaran Penuh",
		Text = "Kamu berhasil mengungkap pencuri manusia sekaligus dalang praktik pesugihan. Semua "
			.. "misteri terpecahkan. Desa Bojongsari benar-benar aman.",
	},
	HardPartial = {
		Title = "Kebenaran yang Belum Utuh",
		Text = "Kamu hanya menemukan satu dari dua pelaku. Sebagian misteri desa Bojongsari masih "
			.. "tersimpan dalam gelap.",
	},
}

NarrativeData.Hints = {
	default = "Coba periksa ulang rumah warga yang belum kamu kunjungi malam ini.",
}

-- Flavor names for EntityAIService sightings, matching the team's accepted narrative
-- revision (see game_naratif.md's "Masukan dari kelompok Desi Fitria" section): mystical
-- entities are "setan gundul" and "methek", not a generic tuyul. Easy mode intentionally
-- has no named entity (light disturbances only, per DESIGN_BRIEF.md's difficulty design).
NarrativeData.EntityNames = {
	Medium = { "setan gundul" },
	Hard = { "setan gundul", "methek" },
}

return NarrativeData
]====]
    },
    {
        path = "game.ReplicatedStorage.Modules.Net.RemoteDefinitions",
        className = "ModuleScript",
        content = [====[-- ReplicatedStorage/Modules/Net/RemoteDefinitions.lua
-- Flat list of RemoteEvent names created under ReplicatedStorage.Remotes by RemoteRegistry.
--
-- IMPORTANT: prompt-triggered actions (collecting a clue, starting dialogue, opening a
-- puzzle, reaching a checkpoint) do NOT need a client->server remote. Roblox's
-- ProximityPrompt.Triggered already only fires after the engine validates distance
-- server-side, so InteractionService listens to that event directly. Remotes below only
-- cover: (a) server -> client pushes, and (b) client -> server follow-ups that happen
-- *after* a prompt UI is already open (choosing a dialogue option, submitting a puzzle
-- answer, submitting an accusation).

return {
	-- Server -> Client
	"Objective/StateChanged",
	"Trust/StateChanged",
	"Investigation/ClueAdded",
	"Dialogue/Node",
	"Puzzle/Data",
	"Puzzle/Result",
	"Horror/Event",
	"Entity/Sighted",
	"Checkpoint/Saved",
	"Checkpoint/Returned",
	"Checkpoint/HintUnlocked",
	"Accusation/Open",
	"Accusation/Result",
	"Night/TimeUpdated",
	"Night/TimeUp",
	"Interaction/Locked",

	-- Client -> Server
	"Dialogue/Choose",
	"Puzzle/Submit",
	"Accusation/Submit",
}
]====]
    },
    {
        path = "game.ReplicatedStorage.Modules.Net.RemoteRegistry",
        className = "ModuleScript",
        content = [====[-- ReplicatedStorage/Modules/Net/RemoteRegistry.lua
-- Server: RemoteRegistry.Init() creates one RemoteEvent per entry in RemoteDefinitions
--         under ReplicatedStorage.Remotes.
-- Server & Client: RemoteRegistry.Get(name) returns the RemoteEvent, waiting for it if
--         the client asks before the server has created it yet.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")

local RemoteDefinitions = require(script.Parent.RemoteDefinitions)

local RemoteRegistry = {}
local cache = {}

local function getFolder()
	local folder = ReplicatedStorage:FindFirstChild("Remotes")
	if folder then
		return folder
	end
	if RunService:IsServer() then
		folder = Instance.new("Folder")
		folder.Name = "Remotes"
		folder.Parent = ReplicatedStorage
		return folder
	end
	return ReplicatedStorage:WaitForChild("Remotes")
end

function RemoteRegistry.Init()
	assert(RunService:IsServer(), "RemoteRegistry.Init() must only run on the server")
	local folder = getFolder()
	for _, path in ipairs(RemoteDefinitions) do
		if not folder:FindFirstChild(path) then
			local remote = Instance.new("RemoteEvent")
			remote.Name = path
			remote.Parent = folder
		end
	end
end

function RemoteRegistry.Get(path)
	local cached = cache[path]
	if cached then
		return cached
	end
	local folder = getFolder()
	local remote = folder:FindFirstChild(path) or folder:WaitForChild(path, 10)
	if not remote then
		warn("[RemoteRegistry] Remote not found after waiting:", path)
	end
	cache[path] = remote
	return remote
end

return RemoteRegistry
]====]
    },
    {
        path = "game.ReplicatedStorage.Modules.Util.AttributeConstants",
        className = "ModuleScript",
        content = [====[-- ReplicatedStorage/Modules/Util/AttributeConstants.lua
-- Matches the interactable attribute contract in ARCHITECTURE.md and
-- MAIN_GAME_SYSTEM_RULES.md §3. Use these constants instead of raw strings anywhere an
-- attribute name or InteractionType value is read or written.

local AttributeConstants = {}

AttributeConstants.InteractionType = {
	Jimpitan = "jimpitan_can",
	Clue = "clue",
	NPC = "npc",
	Puzzle = "puzzle",
	Checkpoint = "checkpoint",
	AccusationBoard = "accusation_board",
}

AttributeConstants.Attributes = {
	InteractionType = "InteractionType",
	JimpitanId = "JimpitanId",
	ClueId = "ClueId",
	ClueText = "ClueText", -- optional flavor text shown when a clue is picked up
	FalseClue = "FalseClue", -- optional bool, Medium/Hard only
	NPCId = "NPCId",
	PuzzleId = "PuzzleId",
	CheckpointId = "CheckpointId",
	PromptText = "PromptText", -- optional ProximityPrompt.ActionText override
	DifficultyOnly = "DifficultyOnly", -- optional: "Easy" | "Medium" | "Hard"
	RequiresClueId = "RequiresClueId", -- optional: soft-lock until this clue is collected
}

return AttributeConstants
]====]
    },
    {
        path = "game.ReplicatedStorage.Modules.Util.Signal",
        className = "ModuleScript",
        content = [====[-- ReplicatedStorage/Modules/Util/Signal.lua
-- Minimal pub-sub helper for internal Controller/Service state changes that don't need
-- to cross the client/server boundary (i.e. don't need a RemoteEvent). Not required by
-- the current Controllers, but available so future UI screens can drive state without
-- per-frame polling, per ROBLOX_UI_SKILL.md §5.

local Signal = {}
Signal.__index = Signal

function Signal.new()
	return setmetatable({ _handlers = {} }, Signal)
end

function Signal:Connect(fn)
	local handlers = self._handlers
	table.insert(handlers, fn)

	local connection = {}
	function connection.Disconnect()
		local index = table.find(handlers, fn)
		if index then
			table.remove(handlers, index)
		end
	end
	return connection
end

function Signal:Fire(...)
	for _, fn in ipairs(self._handlers) do
		task.spawn(fn, ...)
	end
end

return Signal
]====]
    },
}

local function getOrCreatePath(pathStr, className)
	local parts = string.split(pathStr, ".")
	local current = game
	
	-- The first part is always "game" (which is implicit, but parts[1] is "game")
	-- We start from index 2
	for i = 2, #parts - 1 do
		local name = parts[i]
		local child = current:FindFirstChild(name)
		if not child then
			-- If it doesn't exist, create a Folder
			child = Instance.new("Folder")
			child.Name = name
			child.Parent = current
		end
		current = child
	end
	
	local targetName = parts[#parts]
	local target = current:FindFirstChild(targetName)
	if not target then
		target = Instance.new(className)
		target.Name = targetName
		target.Parent = current
	elseif target.ClassName ~= className then
		-- If it exists but class doesn't match, destroy and recreate
		target:Destroy()
		target = Instance.new(className)
		target.Name = targetName
		target.Parent = current
	end
	
	return target
end

local created = 0
local updated = 0
for _, file in ipairs(files) do
	local target = getOrCreatePath(file.path, file.className)
	if target.Source ~= file.content then
		target.Source = file.content
		updated = updated + 1
	else
		created = created + 1 -- already matches
	end
end

-- Also clean up the old EntityAIService under Systems if it exists
local oldAI = game.ServerScriptService:FindFirstChild("GameServer")
if oldAI then
	oldAI = oldAI:FindFirstChild("Systems")
	if oldAI then
		local ai = oldAI:FindFirstChild("EntityAIService")
		if ai then
			ai:Destroy()
			print("Cleaned up old Systems.EntityAIService")
		end
	end
end

return "Sync complete. Created/Verified: " .. created .. ", Updated: " .. updated
